import fs from 'node:fs';
import path from 'node:path';
const dir = process.env.TEMP + '/live';
const z = JSON.parse(fs.readFileSync(path.join(dir, 'zec.json'), 'utf8'));
const zf = (z.fields as any[]).find(x => x.entryId === 'zec-14-4' && x.field === 'terms[0].note');
console.log('zec-14-4 terms[0].note:');
console.log(JSON.stringify(zf?.text));
console.log('');
const e = JSON.parse(fs.readFileSync(path.join(dir, 'exo.json'), 'utf8'));
const bad = (e.fields as any[]).filter(x => /First principle\./.test(x.text));
console.log(`exo fields containing "First principle." : ${bad.length}`);
const multi = bad.filter(x => ((x.text.match(/First principle\./g) ?? []).length) > 1);
console.log(`of which carrying it more than once: ${multi.length}`);
console.log('sample tails:');
for (const m of bad.slice(0, 4)) console.log(`   ${m.entryId} · ${m.field}  ->  ${JSON.stringify(m.text.slice(-130))}`);
console.log('');
const e46 = (e.fields as any[]).find(x => x.entryId === 'exo-12-46' && x.field === 'who');
const tail = e46.text.slice(e46.text.indexOf('Redemptive Purpose:'));
console.log('exo-12-46 who · Redemptive Purpose: ' + JSON.stringify(tail));
