/**
 * Export each Bible book as JSON under public/books/ for lazy loading.
 * Also repairs known KJV dump gaps (Matthew 2:16).
 * Run: npx tsx scripts/exportBookJson.ts
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const outDir = path.join(root, 'public', 'books');

type BibleBook = { name: string; chapters: string[][] };

const bible: BibleBook[] = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'kjv.json'), 'utf8').trim().replace(/^﻿/, '')
);

function cleanText(raw: string): string {
  let t = raw;
  t = t.replace(/\{([^}]*)\}/g, (_m, inner: string) => {
    if (/^[\w\s'.,;:!?-]+$/.test(inner) && !/:/.test(inner) && !/\b(?:Heb|Gr|Chaldee|or)\b/i.test(inner)) {
      return inner;
    }
    return '';
  });
  t = t.replace(/\s+[A-Za-z][\w'...]*:\s*(?:Heb|Gr|Chaldee|or)\b[^.]*\.?/gi, '');
  t = t.replace(/\s{2,}/g, ' ').trim();
  return t;
}

const SLUG: Record<string, string> = {
  Genesis: 'gen', Exodus: 'exo', Leviticus: 'lev', Numbers: 'num', Deuteronomy: 'deu',
  Joshua: 'jos', Judges: 'jdg', Ruth: 'rut', '1 Samuel': '1sa', '2 Samuel': '2sa',
  '1 Kings': '1ki', '2 Kings': '2ki', '1 Chronicles': '1ch', '2 Chronicles': '2ch',
  Ezra: 'ezr', Nehemiah: 'neh', Esther: 'est', Job: 'job', Psalms: 'psa', Proverbs: 'pro',
  Ecclesiastes: 'ecc', 'Song of Solomon': 'sng', Isaiah: 'isa', Jeremiah: 'jer',
  Lamentations: 'lam', Ezekiel: 'ezk', Daniel: 'dan', Hosea: 'hos', Joel: 'jol',
  Amos: 'amo', Obadiah: 'oba', Jonah: 'jon', Micah: 'mic', Nahum: 'nam',
  Habakkuk: 'hab', Zephaniah: 'zep', Haggai: 'hag', Zechariah: 'zec', Malachi: 'mal',
  Matthew: 'mat', Mark: 'mrk', Luke: 'luk', John: 'joh', Acts: 'act', Romans: 'rom',
  '1 Corinthians': '1co', '2 Corinthians': '2co', Galatians: 'gal', Ephesians: 'eph',
  Philippians: 'php', Colossians: 'col', '1 Thessalonians': '1th', '2 Thessalonians': '2th',
  '1 Timothy': '1ti', '2 Timothy': '2ti', Titus: 'tit', Philemon: 'phm', Hebrews: 'heb',
  James: 'jam', '1 Peter': '1pe', '2 Peter': '2pe', '1 John': '1jn', '2 John': '2jn',
  '3 John': '3jn', Jude: 'jud', Revelation: 'rev',
};

/** Standard KJV Matt 2:16 — missing from the source dump (chapter had only 22 verses). */
const MATT_2_16 =
  'Then Herod, when he saw that he was mocked of the wise men, was exceeding wroth, and sent forth, and slew all the children that were in Bethlehem, and in all the coasts thereof, from two years old and under, according to the time which he had diligently enquired of the wise men.';

type JsonVerse = { id: string; chapter: number; verse: number; text: string };

function repairMatthew(chapters: string[][]): string[][] {
  const ch2 = chapters[1];
  if (!ch2 || ch2.length !== 22) return chapters;
  // Dump is missing the slaughter of the innocents between v15 and current v16.
  const fixed = [...ch2];
  fixed.splice(15, 0, MATT_2_16);
  chapters[1] = fixed;
  return chapters;
}

fs.mkdirSync(outDir, { recursive: true });

const registry: {
  slug: string;
  name: string;
  chapters: number;
  verses: number;
}[] = [];

for (const src of bible) {
  const slug = SLUG[src.name];
  if (!slug) {
    console.error('No slug for', src.name);
    process.exit(1);
  }
  let chapters = src.chapters.map(c => [...c]);
  if (src.name === 'Matthew') chapters = repairMatthew(chapters);

  const verses: JsonVerse[] = [];
  chapters.forEach((chapter, cIdx) => {
    const ch = cIdx + 1;
    chapter.forEach((raw, vIdx) => {
      verses.push({
        id: `${slug}-${ch}-${vIdx + 1}`,
        chapter: ch,
        verse: vIdx + 1,
        text: cleanText(raw),
      });
    });
  });

  const payload = {
    slug,
    name: src.name,
    chapters: chapters.length,
    verses: verses.length,
    data: verses,
  };

  fs.writeFileSync(path.join(outDir, `${slug}.json`), JSON.stringify(payload));
  registry.push({
    slug,
    name: src.name,
    chapters: chapters.length,
    verses: verses.length,
  });
  console.log(`${src.name} (${slug}): ${chapters.length} ch, ${verses.length} verses`);
}

// Compact registry for the app (no verse text)
const registryTs = `/** Generated by scripts/exportBookJson.ts — do not edit by hand. */
export interface BookMeta {
  slug: string;
  name: string;
  chapters: number;
  verses: number;
}

export const BOOK_REGISTRY: BookMeta[] = ${JSON.stringify(registry, null, 2)};

export const BOOK_BY_NAME: Record<string, BookMeta> = Object.fromEntries(
  BOOK_REGISTRY.map(b => [b.name, b])
);

export const BOOK_BY_SLUG: Record<string, BookMeta> = Object.fromEntries(
  BOOK_REGISTRY.map(b => [b.slug, b])
);
`;

fs.writeFileSync(path.join(root, 'src', 'data', 'bookRegistry.ts'), registryTs);
console.log('\nWrote public/books/*.json and src/data/bookRegistry.ts');
console.log('Total books:', registry.length, 'Total verses:', registry.reduce((n, b) => n + b.verses, 0));
