export const PART_3 = {
  // Malachi 4:2 -> Luke 1:78-79
  'mal-4-2_Luke 1:78-79': {
    id: 'mal-4-2_Luke 1:78-79',
    anchorRef: 'Malachi 4:2',
    targetRef: 'Luke 1:78-79',
    who: 'Authorship & Context: The Prophet Malachi delivered the final prophetic oracle of the Old Testament canon in Jerusalem (c. 430–400 BC) during the Persian era under Nehemiah\'s governorship. Zechariah the priest, father of John the Baptist, was filled with the Holy Spirit and uttered the Benedictus canticle (Luke 1:67-79) in Judea upon the circumcision of his newborn son (c. 5–4 BC), recorded by Luke the Evangelist (c. AD 60–62). Identified Characters: Yahweh of Hosts speaking through Malachi; the faithful remnant who "fear My name"; the righteous King-Messiah (the Sun of Righteousness); the priest Zechariah; the infant forerunner John; and sinners sitting in the shadow of death. Christological Subject & Referent: Jesus Christ, the Sun of Righteousness (שֶׁמֶשׁ צְדָקָה, Shemesh Tsedaqah) and the Dayspring / Dawn from on High (ἀνατολὴ ἐξ ὕψους). He is the personal divine Dawn who ends four centuries of prophetic silence and spiritual night. Redemptive Purpose: To reveal the tender visceral mercy of God: the Messiah comes not as scorching wrath, but as radiant solar illumination that heals the broken, justifies the ungodly, and guides wandering feet into the pathway of peace.',
    what: 'The glorious poetic and theological fulfillment of the Old Testament\'s concluding messianic promise in Malachi 4:2 ("But unto you that fear my name shall the Sun of righteousness arise with healing in his wings; and ye shall go forth, and grow up as calves of the stall") in Zechariah\'s Benedictus prophecy in Luke 1:78-79: "Through the tender mercy of our God; whereby the dayspring from on high hath visited us, To give light to them that sit in darkness and in the shadow of death, to guide our feet into the way of peace."',
    when: 'Source Horizon: Persian Restoration Era (c. 430 BC), the final book and chapter of the Old Testament. Target Horizon: The dawn of the New Testament era (c. 5–4 BC) in the hill country of Judea.',
    how: 'Messianic solar imagery and canonical exegesis. In Malachi 4:2, the prophet concludes the Hebrew Scriptures with a brilliant solar metaphor: וְזָרְחָה לָכֶם יִרְאֵי שְׁמִי שֶׁמֶשׁ צְדָקָה וּמַרְפֵּא בִּכְנָפֶיהָ (Vezarechah lakhem yir\'ey shemi shemesh tsedaqah u-marpeʾ biknafeha — "And there shall arise for you who fear My name the Sun of Righteousness with healing in His wings / rays / borders"). The noun כָּנָף (kanaf) denotes both the outstretched rays or wings of dawn and the corner borders/fringes (tzitzit) of a garment (as when the woman with the issue of blood touched the kanaf of Jesus\' garment and received healing, Mat 9:20). In Luke 1:78-79, Zechariah translates Malachi\'s Hebrew solar promise into Greek: διὰ σπλάγχνα ἐλέους Θεοῦ ἡμῶν (dia splagchna eleous Theou hēmōn — "because of the tender visceral mercies / deep compassions of our God"), ἐν οἷς ἐπεσκέψατο ἡμᾶς ἀνατολὴ ἐξ ὕψους (en hois epeskepsato hēmas anatolē ex hypsous — "by which the Dayspring / Sunrise / Orient from on high has visited us"). The Greek term ἀνατολή (anatolē) signifies the rising of the sun breaking above the eastern horizon. Christ is the heavenly Sunrise who visits those sitting in spiritual darkness and the shadow of death (ἐν σκότει καὶ σκιᾷ θανάτου) to guide their feet into the way of peace (εἰς ὁδὸν εἰρήνης).',
    why: 'To demonstrate the seamless transition between the Testaments. The last prophetic promise of the Old Testament (Malachi 4) is the first fulfilled reality celebrated at the threshold of the New Testament (Luke 1), proving that the four centuries of prophetic silence did not derail God\'s covenant promises.',
    ultimatePoint: 'Jesus Christ is the Sun of Righteousness and heavenly Dayspring whose rising dispels the long darkness of sin, bringing divine healing, forgiveness, and peace to all who revere His name.',
    personalRelevance: 'Why you need to know this: No matter how dark your past, your circumstances, or your mental struggle may feel, the spiritual night is not permanent; the Sun of Righteousness has risen over your life. What it does for you: It pours warmth, joy, and emotional healing into the cold, wounded places of your soul, liberating you to leap with joy like well-fed calves released from the stall into the sunshine. Relationship with Jesus: Walking with Jesus as your personal Dayspring, stepping into His healing rays every morning and letting His tender mercy guide your steps throughout the day.',
    historicalContext: {
      sourceAuthor: 'Prophet Malachi (c. 430–400 BC)',
      sourceDate: 'c. 430 BC',
      sourceSetting: 'Post-exilic Jerusalem, addressing a cynical, spiritually indifferent generation offering blemished animals to God. Malachi warns of the Day of Judgment but promises the rising of the Sun of Righteousness to the faithful remnant.',
      fulfillmentAuthor: 'Luke the Evangelist (c. AD 60–62, recording Zechariah c. 5–4 BC)',
      fulfillmentDate: 'c. 5–4 BC',
      fulfillmentSetting: 'The hill country of Judea, as the aged priest Zechariah recovers his speech after nine months of silence upon the birth of his son John.',
      redemptiveBridge: 'Across 400 silent years between the Testaments, Malachi\'s setting sun of Old Testament prophecy rises again as the Dayspring of the New Testament in Jesus Christ.',
    },
  },

  // Malachi 4:2 -> Revelation 22:16
  'mal-4-2_Revelation 22:16': {
    id: 'mal-4-2_Revelation 22:16',
    anchorRef: 'Malachi 4:2',
    targetRef: 'Revelation 22:16',
    who: 'Authorship & Context: Malachi; the Apostle John on Patmos receiving the final words of the resurrected Lord. Identified Characters: Malachi; the faithful remnant; the Apostle John; the churches; and Jesus Christ. Christological Subject & Referent: Jesus Christ, the Root and Offspring of David, and the bright and morning Star. Redemptive Purpose: To close both the Old Testament and the New Testament with Christ as the celestial Light of redemption.',
    what: 'The canonical symmetry between the Sun of Righteousness closing the Old Testament in Malachi 4:2 and Christ declaring Himself the Bright and Morning Star at the conclusion of the New Testament in Revelation 22:16: "I Jesus have sent mine angel to testify unto you these things in the churches. I am the root and the offspring of David, and the bright and morning star."',
    when: 'Source: Persian Restoration (c. 430 BC). Target: Patmos Apocalyptic Epilogue (c. AD 95).',
    how: 'Canonical bookend and celestial typology. Malachi concludes the Old Testament with the promise that the Sun of Righteousness will arise (וְזָרְחָה שֶׁמֶשׁ צְדָקָה). Revelation concludes the New Testament and the entire biblical canon with Jesus declaring in the first person: Ἐγώ εἰμι... ὁ ἀστὴρ ὁ λαμπρὸς ὁ πρωϊνός (Egō eimi... ho astēr ho lampros ho prōinos — "I am... the bright and morning star"). The morning star heralds the imminent rising of the sun and the beginning of an eternal day where "there shall be no night there" (Rev 22:5).',
    why: 'To demonstrate that the entire biblical revelation from Genesis to Revelation is enveloped in Christ as the Light of the world.',
    ultimatePoint: 'Jesus Christ is both the Sun of Righteousness and the Bright and Morning Star, whose rising brings an end to the night of human rebellion and inaugurates the eternal day of the New Creation.',
    personalRelevance: 'Why you need to know this: When the world feels darkest, the morning star reminds you that the eternal dawn is about to break. What it does for you: Fills your heart with joyful hope and perseverance, knowing that the night is far spent and the day of Christ\'s return is near. Relationship with Jesus: Looking to Jesus as your Morning Star in every dark hour.',
    historicalContext: {
      sourceAuthor: 'Prophet Malachi (c. 430 BC)',
      sourceDate: 'c. 430 BC',
      sourceSetting: 'Post-exilic Jerusalem.',
      fulfillmentAuthor: 'Apostle John (c. AD 95)',
      fulfillmentDate: 'c. AD 95',
      fulfillmentSetting: 'Patmos vision concluding the Apocalypse.',
      redemptiveBridge: 'The closing chapter of the Old Testament connects directly to the closing chapter of the New Testament in the celestial glory of Christ.',
    },
  },

  // Malachi 4:2 -> 2 Peter 1:19
  'mal-4-2_2 Peter 1:19': {
    id: 'mal-4-2_2 Peter 1:19',
    anchorRef: 'Malachi 4:2',
    targetRef: '2 Peter 1:19',
    who: 'Authorship & Context: Malachi; the Apostle Peter writing his farewell testament before martyrdom in Rome (c. AD 66–67). Identified Characters: Malachi; the Apostle Peter; eyewitnesses of the Transfiguration; and believers holding fast to the prophetic Word. Christological Subject & Referent: Jesus Christ, the Day Star (φωσφόρος) arising in the hearts of believers. Redemptive Purpose: To establish the supreme reliability of the prophetic Scriptures until the dawn of Christ\'s return.',
    what: 'The arising of the Sun of Righteousness in Malachi 4:2 reflected in Peter\'s exhortation to heed the prophetic word until the Day Star arises in 2 Peter 1:19: "We have also a more sure word of prophecy; whereunto ye do well that ye take heed, as unto a light that shineth in a dark place, until the day dawn, and the day star arise in your hearts."',
    when: 'Source: Persian Restoration (c. 430 BC). Target: Peter\'s farewell testament (c. AD 66–67) in Rome.',
    how: 'Epistemological and eschatological exegesis. Peter compares the prophetic Scriptures to a lamp shining in a squalid, murky place (ἐν αὐχμηρῷ τόπῳ). But this lamp points toward a greater reality: ἕως οὗ ἡμέρα διαυγάσῃ καὶ φωσφόρος ἀνατείλῃ ἐν ταῖς καρδίαις ὑμῶν (heōs hou hēmera diaugasē kai phōsphoros anateilē en tais kardiais hymōn — "until the day dawns and the light-bearer / morning star / day-star arises in your hearts"). The noun φωσφόρος (phōsphoros — light-bringer) echoes Malachi\'s rising Sun of Righteousness, signifying both the internal subjective illumination of Christ\'s glory in the heart and His objective historical return.',
    why: 'To assure believers that the prophetic word is not a human myth or fairy tale, but God\'s steady beacon guiding us until the full radiance of Christ appears.',
    ultimatePoint: 'The prophetic word points toward Jesus Christ, the true Day Star, whose rising in our hearts and at His return dispels all spiritual darkness.',
    personalRelevance: 'Why you need to know this: In times of doubt, cultural confusion, or dark trials, Scripture is a steady, burning lamp for your soul. What it does for you: Anchors your faith in the infallible Word of God until the warmth of Christ\'s presence fills your heart with unshakable clarity. Relationship with Jesus: Allowing the living Christ to rise as the Day Star in your heart each day.',
    historicalContext: {
      sourceAuthor: 'Prophet Malachi (c. 430 BC)',
      sourceDate: 'c. 430 BC',
      sourceSetting: 'Malachi\'s post-exilic warning.',
      fulfillmentAuthor: 'Apostle Peter (c. AD 66–67, Rome)',
      fulfillmentDate: 'c. AD 66–67',
      fulfillmentSetting: 'Rome, facing imminent execution under Nero.',
      redemptiveBridge: 'From Malachi\'s prophetic beacon to Peter\'s apostolic certainty in the arising Day Star.',
    },
  },

  // Malachi 4:2 -> Matthew 17:2
  'mal-4-2_Matthew 17:2': {
    id: 'mal-4-2_Matthew 17:2',
    anchorRef: 'Malachi 4:2',
    targetRef: 'Matthew 17:2',
    who: 'Authorship & Context: Malachi; the Apostle Matthew recording the Transfiguration of Jesus on the high mountain (c. AD 30). Identified Characters: Jesus; Peter, James, and John; Moses and Elijah appearing in glory; and the Father speaking from the cloud. Christological Subject & Referent: Jesus Christ, whose face shone as the sun, unveiling His uncreated divine glory. Redemptive Purpose: To provide the inner circle of disciples with a preview of the glorious kingdom reign of the Sun of Righteousness.',
    what: 'The radiant solar majesty of the Sun of Righteousness in Malachi 4:2 manifested in the Transfiguration of Jesus in Matthew 17:2: "And was transfigured before them: and his face did shine as the sun, and his raiment was white as the light."',
    when: 'Source: Persian Restoration (c. 430 BC). Target: High mountain in Galilee / Mount Hermon (c. AD 30).',
    how: 'Christophanic and eschatological manifestation. In Matthew 17:2, Jesus is transfigured: μετεμορφώθη (metemorphōthē — the outward veil of His humanity pulled aside to reveal His essential divine nature). Matthew notes: καὶ ἔλαμψεν τὸ πρόσωπον αὐτοῦ ὡς ὁ ἥλιος (kai elampsen to prosōpon autou hōs ho hēlios — "and His face shone as the sun"). The radiant solar countenance of Jesus directly fulfills Malachi\'s prophecy of the Sun of Righteousness (שֶׁמֶשׁ צְדָקָה). Moses (representing the Law) and Elijah (representing the Prophets) appear beside Him, and the Father declares: "This is my beloved Son: hear him!"',
    why: 'To demonstrate to the disciples that Jesus was not merely a suffering mortal destined for the cross, but the glorious Lord of glory whose kingdom will blaze with uncreated light.',
    ultimatePoint: 'The Transfiguration revealed Jesus Christ as the true Sun of Righteousness, whose radiant divine glory shines brighter than the sun.',
    personalRelevance: 'Why you need to know this: The Jesus who forgives your sins is the glorious God of unapproachable light before whom Moses and Elijah bow. What it does for you: Fills your heart with deep reverence, awe, and worship, curing casual attitudes toward God. Relationship with Jesus: Beholding the radiant glory of Jesus and being transformed into His image from glory to glory.',
    historicalContext: {
      sourceAuthor: 'Prophet Malachi (c. 430 BC)',
      sourceDate: 'c. 430 BC',
      sourceSetting: 'Jerusalem oracle.',
      fulfillmentAuthor: 'Apostle Matthew (c. AD 60–68, recording c. AD 30)',
      fulfillmentDate: 'c. AD 30',
      fulfillmentSetting: 'High mountain in northern Israel (likely Mount Hermon).',
      redemptiveBridge: 'The prophetic solar promise of Malachi becomes visible historical reality on the Mount of Transfiguration.',
    },
  },

  // Malachi 4:5-6 -> Luke 1:17 / Matthew 17:11-13
  'mal-4-5_Luke 1:17 / Matthew 17:11-13': {
    id: 'mal-4-5_Luke 1:17 / Matthew 17:11-13',
    anchorRef: 'Malachi 4:5-6',
    targetRef: 'Luke 1:17 / Matthew 17:11-13',
    who: 'Authorship & Context: The Prophet Malachi concluded the Old Testament prophetic corpus with the promise of Elijah\'s return (c. 430 BC). Gabriel the Archangel announced the birth of John the Baptist to Zechariah in the Temple (c. 5 BC), recorded by Luke. Jesus Himself identified John as the promised Elijah following the Transfiguration (c. AD 30), recorded by Matthew. Identified Characters: Yahweh; the Prophet Elijah; the Prophet Malachi; the Archangel Gabriel; Zechariah the priest; John the Baptist; the disciples Peter, James, and John; and Jesus of Nazareth. Christological Subject & Referent: Jesus Christ, the coming Lord before whose face the prophetic forerunner prepares the way. Redemptive Purpose: To authenticate John the Baptist\'s ministry as the bridge between the Old and New Covenants, calling Israel to repentance before the King.',
    what: 'The prophetic promise of Elijah the forerunner in Malachi 4:5-6 ("Behold, I will send you Elijah the prophet before the coming of the great and dreadful day of the LORD: And he shall turn the heart of the fathers to the children") fulfilled in Gabriel\'s annunciation in Luke 1:17 ("And he shall go before him in the spirit and power of Elias... to make ready a people prepared for the Lord") and Jesus\' confirmation in Matthew 17:11-13 ("Elias is come already... Then the disciples understood that he spake unto them of John the Baptist").',
    when: 'Source Horizon: Persian Restoration (c. 430 BC). Target Horizon: The forerunner\'s ministry (c. 5 BC – AD 30) in Judea.',
    how: 'Typological and prophetic identification. Malachi promises: הִנֵּה אָנֹכִי שֹׁלֵחַ לָכֶם אֵת אֵלִיָּה הַנָּבִיא לִפְנֵי בּוֹא יוֹם יְהוָה הַגָּדוֹל וְהַנּוֹרָא (Hineh ʾanokhi sholeach lakhem ʾet ʾEliyah hanna-viʾ liphney boʾ yom Yahweh haggadol vehannoraʾ — "Behold, I will send you Elijah the prophet before the coming of the great and terrible day of Yahweh"). Gabriel clarifies that this was not the literal physical resurrection of the historical Tishbite, but a prophet coming ἐν πνεύματι καὶ δυνάμει Ἠλίου (en pneumati kai dynamei Ēliou — "in the spirit and power of Elijah"), carrying the identical prophetic mantle of fearless confrontation, ascetic wilderness lifestyle, and baptism of repentance. In Matthew 17:11-13, Jesus confirms: Ἠλίας ἤδη ἦλθεν (Ēlias ēdē ēlthen — "Elijah has already come, and they knew him not, but have done unto him whatsoever they listed... Then the disciples understood that He spoke to them of John the Baptist").',
    why: 'To demonstrate that God sent a mighty prophetic herald to prepare hearts before Christ appeared, ensuring that the covenant people had ample warning and opportunity to turn in repentance to their Messiah.',
    ultimatePoint: 'John the Baptist fulfilled the prophecy of Elijah\'s return, ministering in the spirit and power of Elijah to prepare the hearts of the people for the arrival of the Lord Jesus Christ.',
    personalRelevance: 'Why you need to know this: God always prepares the heart before He enters with His saving, transforming presence; true revival is always preceded by genuine repentance. What it does for you: It dismantles superficial religious complacency, calling you to honesty, humility, and wholehearted alignment with God\'s truth. Relationship with Jesus: Preparing room in your heart every day for King Jesus to rule and reign without rival.',
    historicalContext: {
      sourceAuthor: 'Prophet Malachi (c. 430 BC)',
      sourceDate: 'c. 430 BC',
      sourceSetting: 'The final words of the Old Testament prophetic canon, placing a sentinel of hope on the watchtower of Israel.',
      fulfillmentAuthor: 'Luke the Evangelist & Apostle Matthew (c. AD 60–68)',
      fulfillmentDate: 'c. 5 BC / AD 30',
      fulfillmentSetting: 'The golden altar of incense in the Jerusalem Temple (Gabriel), and the slopes of Mount Hermon (Jesus).',
      redemptiveBridge: 'Elijah\'s mantle passes across 400 years to John the Baptist at the Jordan River, pointing directly to Jesus as the Lamb of God.',
    },
  },

  // Matthew 1:22-23 -> Isaiah 7:14
  'mat-1-22_Isaiah 7:14': {
    id: 'mat-1-22_Isaiah 7:14',
    anchorRef: 'Matthew 1:22-23',
    targetRef: 'Isaiah 7:14',
    who: 'Authorship & Context: The Apostle Matthew wrote his Gospel in Antioch/Judea (c. AD 60–68) to Jewish-Christian believers, demonstrating that Jesus is the authentic Messiah of Israel who fulfills the Old Testament Scriptures. The Prophet Isaiah delivered the virgin-birth prophecy in Jerusalem (c. 734 BC) during the Syro-Ephraimite crisis to wicked King Ahaz. Identified Characters: Yahweh the Lord; the Prophet Isaiah; wicked King Ahaz refusing to ask for a sign; the royal House of David; the virgin mother (Mary); Joseph the son of David receiving angelic counsel; and the divine child. Christological Subject & Referent: Jesus Christ, Immanuel (עִמָּנוּאֵל / Ἐμμανουήλ) — "God with us". He is the virgin-conceived Son who unites uncreated deity and authentic sinless humanity in one undivided Person. Redemptive Purpose: To prove that the Messiah\'s entrance into the human race was entirely supernatural, bypassing the corrupted federal headship of fallen Adam while taking genuine human nature to redeem humanity.',
    what: 'The apostolic retrospective and direct prophetic fulfillment connecting Matthew 1:22-23 ("Now all this was done, that it might be fulfilled which was spoken of the Lord by the prophet, saying, Behold, a virgin shall be with child, and shall bring forth a son, and they shall call his name Emmanuel, which being interpreted is, God with us") to Isaiah 7:14: "Therefore the Lord himself shall give you a sign; Behold, a virgin shall conceive, and bear a son, and shall call his name Immanuel."',
    when: 'Source Horizon: Apostolic New Testament Era (c. AD 60–68, recording Christ\'s birth c. 5–4 BC). Target Horizon: Divided Monarchy / Syro-Ephraimite Crisis (c. 734 BC) in Jerusalem.',
    how: 'Apostolic sensus plenior and linguistic vindication. In Isaiah 7:14, the sign is given to the collective House of David (לָכֶם, lakhem — plural): לָכֵן יִתֵּן אֲדֹנָי הוּא לָכֶם אוֹת הִנֵּה הָעַלְמָה הָרָה וְיֹלֶדֶת בֵּן וְקָרָאת שְׁמוֹ עִמָּנוּאֵל (Lakhen yitten ʾAdonay hu lakhem ʾot: hineh ha-ʿalmah harah veyoledet ben veqarat shemo ʿImmanu ʾEl — "Therefore the Lord Himself shall give you a sign: Behold, the maiden/virgin [עַלְמָה, ʿalmah] is with child and bearing a son, and shall call His name Immanuel"). In the pre-Christian Jewish Septuagint translation (c. 250 BC in Alexandria), Jewish translators translated the Hebrew עַלְמָה into the explicit Greek noun ἡ παρθένος (hē parthenos — strictly and exclusively a virgin), showing ancient Jewish understanding. Matthew, writing under divine inspiration, confirms this exact reading: Ἰδοὺ ἡ παρθένος ἐν γαστρὶ ἕξει καὶ τέξεται υἱόν, καὶ καλέσουσιν τὸ ὄνομα αὐτοῦ Ἐμμανουήλ, ὅ ἐστιν μεθερμηνευόμενον Μεθ\' ἡμῶν ὁ Θεός (Idou hē parthenos en gastri hexei kai texetai huion, kai kalesousin to onoma autou Emmanouēl, ho estin methermēneuomenon Meth\' hēmōn ho Theos). The virgin conception was necessary because a biological child of Adam would inherit Adam\'s fallen nature and guilt. The Holy Spirit overshadowed Mary so that the child born was the holy Son of God, uniting true deity (אֵל, ʾEl) with human nature: "God with us" (עִמָּנוּ, ʿimmanu).',
    why: 'To demonstrate that the Incarnation is the miraculous pinnacle of redemptive history. God did not send an angel or a mere human prophet to save us; God Himself stepped into the human family as an infant through the womb of a virgin.',
    ultimatePoint: 'Jesus Christ fulfilled Isaiah 7:14 through His supernatural conception by the Holy Spirit in the womb of the virgin Mary, uniting eternal deity with sinless humanity as Immanuel—God with us.',
    personalRelevance: 'Why you need to know this: You are never alone, forsaken, or abandoned in this universe; through the incarnation of Jesus, God is personally, permanently, and intimately with you. What it does for you: It banishes loneliness, dread, and despair, assuring you that your Savior understands your human weaknesses, tears, and struggles from the inside. Relationship with Jesus: Abiding in Jesus as Immanuel, walking each day in the joyful awareness that God is with you in every trial and victory.',
    historicalContext: {
      sourceAuthor: 'Apostle Matthew (c. AD 60–68, Judea/Antioch)',
      sourceDate: 'c. 5–4 BC / AD 60',
      sourceSetting: 'Antioch/Judea, demonstrating to the Jewish community that the birth of Jesus of Nazareth was the precise fulfillment of their Hebrew prophets.',
      fulfillmentAuthor: 'Prophet Isaiah (c. 740–680 BC, Jerusalem)',
      fulfillmentDate: 'c. 734 BC',
      fulfillmentSetting: 'The royal palace of Jerusalem under siege by the armies of Syria and Northern Israel. Isaiah confronted Ahaz at the conduit of the upper pool.',
      redemptiveBridge: 'Across seven centuries, Isaiah\'s prophecy to the trembling House of David is fulfilled when the angel announces the conception of Immanuel to Joseph, son of David.',
    },
  },

  // Matthew 1:23 -> Isaiah 7:14
  'mat-1-23_Isaiah 7:14': {
    id: 'mat-1-23_Isaiah 7:14',
    anchorRef: 'Matthew 1:22-23',
    targetRef: 'Isaiah 7:14',
    who: 'Authorship & Context: Matthew recording the angel\'s message to Joseph; Isaiah delivering God\'s sign. Identified Characters: God; the virgin Mary; Joseph; Isaiah; and Immanuel. Christological Subject & Referent: Jesus Christ as Immanuel, God in our nature. Redemptive Purpose: To establish the Hypostatic Union of deity and humanity.',
    what: 'The translation and theological revelation of the name Immanuel in Matthew 1:23: "Behold, a virgin shall be with child, and shall bring forth a son, and they shall call his name Emmanuel, which being interpreted is, God with us" fulfilling Isaiah 7:14.',
    when: 'Source: Apostolic Era (c. AD 60). Target: Isaiah\'s prophecy (c. 734 BC).',
    how: 'Theological translation and incarnation theology. Matthew translates עִמָּנוּאֵל as Μεθ\' ἡμῶν ὁ Θεός (Meth\' hēmōn ho Theos). The preposition μετά (with) with the genitive denotes covenant solidarity, presence, and companionship. God has not stayed distant in transcendent majesty; He has tabernacled among us.',
    why: 'To reveal that redemption required God to become man.',
    ultimatePoint: 'The name Immanuel signifies that in Jesus Christ, God has entered into perpetual covenant solidarity with humanity.',
    personalRelevance: 'Why you need to know this: God did not send a surrogate; He came Himself. What it does for you: Delivers from the feeling that God is distant or indifferent to your pain. Relationship with Jesus: Knowing Jesus as God with you in every moment of life.',
    historicalContext: {
      sourceAuthor: 'Apostle Matthew (c. AD 60)',
      sourceDate: 'c. AD 60',
      sourceSetting: 'Joseph\'s dream in Nazareth.',
      fulfillmentAuthor: 'Prophet Isaiah (c. 734 BC)',
      fulfillmentDate: 'c. 734 BC',
      fulfillmentSetting: 'Jerusalem under threat.',
      redemptiveBridge: 'The prophetic name Immanuel bridges directly to the manger and the cross.',
    },
  },

  // Romans 5:14 -> 1 Corinthians 15:22
  'rom-5-14_1 Corinthians 15:22': {
    id: 'rom-5-14_1 Corinthians 15:22',
    anchorRef: 'Romans 5:14',
    targetRef: '1 Corinthians 15:22',
    who: 'Authorship & Context: The Apostle Paul wrote Romans from Corinth (c. AD 57) to unfold the forensic and covenant architecture of the gospel. Paul wrote 1 Corinthians from Ephesus (c. AD 55) to defend the bodily resurrection of the dead against philosophical skepticism in Corinth. Identified Characters: The first Adam (the biological and federal head of fallen humanity); the Last Adam, Jesus Christ (the federal head of the redeemed new creation); and the two humanities represented by each head. Christological Subject & Referent: Jesus Christ, the Last Adam (ὁ ἔσχατος Ἀδάμ) and the second Man (ὁ δεύτερος ἄνθρωπος). Where the first Adam fell into sin and dragged the human race into condemnation and death, Christ obeyed perfectly, conquered death through His resurrection, and became a life-giving Spirit (πνεῦμα ζῳοποιοῦν). Redemptive Purpose: To unveil the biblical doctrine of federal headship: our condemnation in Adam was total and unearned by our personal acts, and therefore our justification in Christ is total, unearned, and secured through faith in His finished work.',
    what: 'The apostolic harmonization of covenant federal headship connecting Romans 5:14 ("Nevertheless death reigned from Adam to Moses, even over them that had not sinned after the similitude of Adam\'s transgression, who is the figure of him that was to come") to 1 Corinthians 15:21-22: "For since by man came death, by man came also the resurrection of the dead. For as in Adam all die, even so in Christ shall all be made alive."',
    when: 'Source Horizon: Mid-1st Century Apostolic Era (c. AD 57), written to Rome. Target Horizon: Mid-1st Century Apostolic Era (c. AD 55), written to Corinth.',
    how: 'Harmonious Pauline theology of the Two Adams and covenant typology. In Romans 5:14, Paul explicitly identifies the first man Adam as a prophetic type: ὅς ἐστιν τύπος τοῦ μέλλοντος (hos estin typos tou mellontos — "who is a type / figure / representative imprint of the One who was to come"). Adam was a type not in his moral failure, but in his federal, representative headship: what Adam did determined the destiny of all who were in him. In 1 Corinthians 15:21-22, Paul develops this identical architecture: ὥσπερ γὰρ ἐν τῷ Ἀδὰμ πάντες ἀποθνῄσκουσιν, οὕτως καὶ ἐν τῷ Χριστῷ πάντες ζωοποιηθήσονται (hōsper gar en tō Adam pantes apothnēskousin, houtōs kai en tō Christō pantes zōopoiēthēsontai — "For just as in Adam all die, in this manner also in Christ all shall be made alive"). In verse 45, Paul adds: Ἐγένετο ὁ πρῶτος ἄνθρωπος Ἀδὰμ εἰς ψυχὴν ζῶσαν, ὁ ἔσχατος Ἀδὰμ (eschatos Adam) εἰς πνεῦμα ζῳοποιοῦν (pneuma zōopoioun) — "The first man Adam became a living soul; the Last Adam became a life-giving Spirit". The first Adam brought sin, condemnation, and death (מָוֶת, mavet / θάνατος, thanatos); the Last Adam brings righteousness, justification, and indestructible resurrection life (ζωή, zōē).',
    why: 'To establish the absolute certainty of the believer\'s resurrection and justification. If Adam\'s single act of disobedience was powerful enough to condemn all united to him, how much more is Christ\'s perfect obedience and resurrection powerful enough to secure eternal life for all who are united to Him by faith.',
    ultimatePoint: 'Jesus Christ is the Last Adam and federal Head of the New Creation: just as all united to the first Adam inherit physical and spiritual death, so all united to Christ by faith receive eternal justification and bodily resurrection life.',
    personalRelevance: 'Why you need to know this: Your identity before God is no longer defined by the fallen, broken heritage of Adam, but by the victorious, righteous standing of Jesus Christ. What it does for you: It shatters despair over personal weakness, assuring you that you have been completely transferred out of the dominion of death and into the unshakeable kingdom of life in Christ. Relationship with Jesus: Abiding in Jesus as your new federal Head, drawing your daily life, strength, and righteousness from His indwelling Spirit.',
    historicalContext: {
      sourceAuthor: 'Apostle Paul (c. AD 57, Corinth)',
      sourceDate: 'c. AD 57',
      sourceSetting: 'Corinth, systematically setting forth the universal scope of the gospel to the Roman church before his planned journey to Spain.',
      fulfillmentAuthor: 'Apostle Paul (c. AD 55, Ephesus)',
      fulfillmentDate: 'c. AD 55',
      fulfillmentSetting: 'Ephesus, writing to Corinth where Greek philosophical dualism led some believers to deny the physical resurrection of the dead.',
      redemptiveBridge: 'The two great federal heads of cosmic history—the first Adam in the Garden of Eden and the Last Adam in the Garden of Gethsemane and Golgotha—define the entire drama of redemption.',
    },
  },
};
