export const PART_2 = {
  // Exodus 12:46 -> John 19:36
  'exo-12-46_John 19:36': {
    id: 'exo-12-46_John 19:36',
    anchorRef: 'Exodus 12:46',
    targetRef: 'John 19:36',
    who: 'Authorship & Context: Moses recorded the institution of the Passover in Exodus 12 on the eve of the 10th plague in Egypt (c. 1446 BC). The Apostle John, writing in Ephesus (c. AD 85–95), stood as the sole eyewitness apostle at the foot of the cross beside Mary (John 19:25-27,35). Identified Characters: Yahweh commanding the paschal ordinance; the destroyer executing judgment; the Hebrew households sheltered by blood; Roman soldiers executing the crucifixion; the two crucified thieves whose legs were broken; and Jesus of Nazareth. Singular or Many: Singular body, many executioners. One Lamb is kept whole; the soldiers and the two other crucified men are the many around that one body. Christological Subject & Referent: Jesus Christ, the true Paschal Lamb (τὸ πάσχα ἡμῶν ἐτύθη Χριστός, 1 Cor 5:7). His physical body remained completely unbroken in accordance with divine decree. Redemptive Purpose: To prove that Jesus\' death was not a chaotic Roman execution, but the sovereignly governed fulfillment of the Passover lamb whose sacrifice shields all believers from the wrath of God.',
    what: 'The precise historical and typological fulfillment of the Passover ordinance ("neither shall ye break a bone thereof", Ex 12:46; Num 9:12; Psa 34:20) in the crucifixion of Jesus Christ recorded in John 19:36: "For these things were done, that the scripture should be fulfilled, A bone of him shall not be broken."',
    when: 'Source Horizon: The Exodus from Egypt (c. 1446 BC), 14th of Nisan. Target Horizon: AD 30/33 on Preparation Day of the Passover at Golgotha outside Jerusalem.',
    how: 'Apostolic eyewitness testimony and typological fulfillment. In Exodus 12:46, the statute regarding the paschal lamb specifies: וְעֶצֶם לֹא־תִשְׁבְּרוּ־בוֹ (ve\'etsem lo-tishberu-vo — "and a bone you shall not break in it"). John witnesses the Roman soldiers breaking the legs (crurifragium) of the two thieves to accelerate asphyxiation before the Sabbath began. But when they came to Jesus and saw that He was already dead, they did not break His legs; instead, one soldier pierced His side with a spear. John cites this as direct divine necessity: ἵνα ἡ γραφὴ πληρωθῇ (hina hē graphē plērōthē — "in order that the Scripture might be fulfilled"): Ὀστοῦν οὐ συντριβήσεται αὐτοῦ (Ostoun ou syntribēsetai autou — "A bone of Him shall not be broken"). The passive verb συντριβήσεται (syntribēsetai, from syntribō — to shatter, crush, or break into fragments) confirms that the Father sovereignly preserved His Son\'s sacrificial body intact, validating Him as the spotless, unblemished Passover Lamb whose offering is eternally perfect and complete.',
    why: 'To demonstrate that Jesus is the authentic antitype of the Exodus Passover. In God\'s redemptive design, the lamb that shielded Israel from the Angel of Death pointed directly to Jesus, whose unbroken wholeness signifies the perfect preservation and eternal efficacy of His atoning sacrifice.',
    ultimatePoint: 'Jesus Christ is the true Passover Lamb whose bones were supernaturally preserved from being broken, confirming that His death was the sovereign fulfillment of the ancient covenant sacrifice that delivers us from the wrath of God.',
    personalRelevance: 'Why you need to know this: When judgment falls upon a broken and fallen world, you are completely safe under the protective blood of the true Passover Lamb. What it does for you: It removes the dread of divine condemnation, assuring you that just as the destroyer passed over every house marked with the blood, so God\'s judgment passes over you forever in Christ. Relationship with Jesus: Walking with Jesus means living in continual gratitude to Him as your Passover Lamb, celebrating your deliverance from the spiritual bondage of sin and walking in newness of life.',
    historicalContext: {
      sourceAuthor: 'Moses (c. 1446–1406 BC)',
      sourceDate: 'c. 1446 BC',
      sourceSetting: 'The night of the tenth plague in Egypt, when the blood of an unblemished yearling lamb on the doorposts protected the firstborn of Israel.',
      fulfillmentAuthor: 'Apostle John (c. AD 85–95, eyewitness c. AD 30/33)',
      fulfillmentDate: 'c. AD 30/33',
      fulfillmentSetting: 'Mount Calvary outside Jerusalem at twilight on Preparation Day, as the priests were slaughtering the Passover lambs in the Temple.',
      redemptiveBridge: 'The blood applied to the wooden doorposts in Egypt prefigures the blood of Jesus shed upon the wooden beams of the cross for the salvation of all who believe.',
    },
  },

  // Numbers 21:9 -> John 3:14-15
  'num-21-9_John 3:14-15': {
    id: 'num-21-9_John 3:14-15',
    anchorRef: 'Numbers 21:9',
    targetRef: 'John 3:14-15',
    who: 'Authorship & Context: Moses recorded the rebellion of Israel and the provision of the bronze serpent in Numbers 21 during the 40-year wilderness journey. Jesus Himself, in dialogue with Nicodemus (recorded by the Apostle John, c. AD 85–95), used this historic event to explain the divine necessity of His crucifixion. Identified Characters: Yahweh sending judgment; Moses interceding and fashioning the serpent; the rebellious dying Israelites bitten by fiery serpents; Nicodemus the Pharisee; and Jesus the Son of Man. Christological Subject & Referent: Jesus Christ, the Son of Man who must be lifted up (ὑψωθῆναι δεῖ τὸν Υἱὸν τοῦ ἀνθρώπου). He is the sinless One made in the likeness of sinful flesh (Rom 8:3), taking the full venom of divine judgment on the pole of the cross. Redemptive Purpose: To reveal the simple, universal principle of saving faith: just as a dying Israelite lived simply by looking upon the lifted serpent, so any sinner who looks to the crucified Christ in faith is delivered from eternal death.',
    what: 'The prophetic and typological fulfillment of the bronze serpent on the pole (Num 21:9) in Jesus\' declaration of His crucifixion and saving mission: "And as Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up: That whosoever believeth in him should not perish, but have eternal life" (John 3:14-15).',
    when: 'Source Horizon: Wilderness Wanderings (c. 1406 BC) along the way of the Red Sea around Edom. Target Horizon: Jesus\' dialogue with Nicodemus in Jerusalem c. AD 30.',
    how: 'Typological exegesis and linguistic correspondence. In Numbers 21:9, Moses fashioned a נְחַשׁ נְחֹשֶׁת (nechash nechoshet — a serpent of bronze/copper) and set it upon a pole or military standard (עַל־נֵס, ʿal-nes). The wordplay between נָחָשׁ (nachash — serpent) and נְחֹשֶׁת (nechoshet — bronze) is intentional: bronze in Scripture represents judgment endured, and the serpent represents sin and the curse judged in its own likeness. When anyone bitten looked (וְהִבִּיט, vehibbit — gazed attentively with expectation) toward the bronze serpent, he lived (וָחָי, vachay). Jesus transposes this type into the supreme soteriological reality: καθὼς Μωϋσῆς ὕψωσεν τὸν ὄφιν ἐν τῇ ἐρήμῳ, οὕτως ὑψωθῆναι δεῖ τὸν Υἱὸν τοῦ ἀνθρώπου (kathōs Mōysēs hypsōsen ton ophin en tē erēmō, houtōs hypsōthēnai dei ton Huion tou anthrōpou — "Just as Moses lifted up the serpent in the wilderness, in this manner it is divinely necessary [δεῖ, dei — divine imperative of redemption] for the Son of Man to be lifted up"). The verb ὑψόω (hypsoō — to lift up) in John\'s Gospel carries a profound double meaning: the physical lifting up of Jesus upon the cross of execution, and His simultaneous glorification and cosmic exaltation as King. Jesus was made "sin for us, who knew no sin" (2 Cor 5:21), bearing the curse upon the tree so that πᾶς ὁ πιστεύων (pas ho pisteuōn — "everyone who believes") should not perish.',
    why: 'To demonstrate to Nicodemus and to all humanity that salvation cannot be attained by moral reformation, ritual washings, or Torah pedigree. Fallen humanity is fatally infected with the lethal venom of sin; salvation comes exclusively by looking in faith to the One who took the curse upon Himself.',
    ultimatePoint: 'The bronze serpent lifted up in the desert was the historic shadow of Jesus Christ being lifted up upon the cross: taking the full curse of our sin upon Himself so that anyone who looks upon Him in faith is instantly healed and granted eternal life.',
    personalRelevance: 'Why you need to know this: You do not need to clean yourself up, earn merit, or perform heroic spiritual deeds to be saved; you only need to look in faith to the crucified Savior. What it does for you: It frees you from the paralyzing exhaustion of self-righteousness, assuring you that one look of genuine faith upon Jesus cancels the deadly poison of sin, guilt, and condemnation in your life. Relationship with Jesus: Walking with Jesus means keeping your gaze continually fixed upon Him on the cross, drawing fresh life, healing, and spiritual vigor from His finished sacrifice every day.',
    historicalContext: {
      sourceAuthor: 'Moses (c. 1446–1406 BC)',
      sourceDate: 'c. 1406 BC',
      sourceSetting: 'The rugged desert south of the Dead Sea, where Israel rebelled against God and Moses, complaining about the manna, and was struck by deadly venomous serpents.',
      fulfillmentAuthor: 'Apostle John (c. AD 85–95, recording Christ c. AD 30)',
      fulfillmentDate: 'c. AD 30',
      fulfillmentSetting: 'Jerusalem at night, instructing Nicodemus, a master of Israel who did not comprehend how a person could be born again from above.',
      redemptiveBridge: 'From the wooden pole in the wilderness where physical life was restored by looking, to the wooden cross on Calvary where eternal life is bestowed upon all who believe.',
    },
  },

  // Numbers 21:8 -> John 3:14-15
  'num-21-8_John 3:14-15': {
    id: 'num-21-8_John 3:14-15',
    anchorRef: 'Numbers 21:8',
    targetRef: 'John 3:14-15',
    who: 'Authorship & Context: Moses recorded Yahweh\'s command to make a fiery serpent. Jesus Christ expounded this divine command to Nicodemus. Identified Characters: Yahweh commanding the provision; the dying Israelites; and the Son of Man. Christological Subject & Referent: Jesus Christ as the lifted-up Savior. Redemptive Purpose: To prove that deliverance from judgment is entirely a divine provision accessed by faith alone.',
    what: 'The divine command in Numbers 21:8 ("Make thee a fiery serpent, and set it upon a pole: and it shall come to pass, that every one that is bitten, when he looketh upon it, shall live") fulfilled in Christ\'s lifting up in John 3:14-15 for the salvation of all who believe.',
    when: 'Source: Wilderness Era (c. 1406 BC). Target: Apostolic Gospel Era (c. AD 30).',
    how: 'Soteriological typology. In Numbers 21:8, Yahweh commands Moses to make a שָׂרָף (saraph — fiery burning serpent), embodying the very judgment destroying the camp. In John 3:14-15, Christ fulfills this by taking the form of sinful flesh to condemn sin in the flesh (Rom 8:3). The Greek verb ὑψωθῆναι (hypsōthēnai — to be lifted up) denotes the cross as the divine standard of salvation. Faith is defined as looking (βλέπω / πιστεύω): looking away from one\'s wounds to God\'s provision.',
    why: 'To illustrate that salvation is outside of human resources: a dying person cannot cure snakebite from within, but must look outside themselves to God\'s lifted standard.',
    ultimatePoint: 'God\'s command to look upon the lifted bronze serpent to escape physical death pointed forward to the cross, where looking to the lifted Son of Man in faith delivers from eternal death.',
    personalRelevance: 'Why you need to know this: Deliverance from sin cannot be manufactured by human willpower; you must look outside yourself to Christ. What it does for you: It gives you instant peace in times of moral failure, reminding you to look to Jesus rather than stare at your own wounds. Relationship with Jesus: Abiding in Jesus means continually looking unto Him, the author and finisher of your faith.',
    historicalContext: {
      sourceAuthor: 'Moses (c. 1446–1406 BC)',
      sourceDate: 'c. 1406 BC',
      sourceSetting: 'Sinai/Edom wilderness with Israel dying of serpent venom.',
      fulfillmentAuthor: 'Apostle John (c. AD 85–95)',
      fulfillmentDate: 'c. AD 30',
      fulfillmentSetting: 'Jerusalem dialogue with Nicodemus.',
      redemptiveBridge: 'The pole of divine remedy in the desert prefigures the cross on Calvary.',
    },
  },

  // Joshua 5:13-15 -> Revelation 19:11-16
  'jos-5-14_Revelation 19:11-16': {
    id: 'jos-5-14_Revelation 19:11-16',
    anchorRef: 'Joshua 5:13-15',
    targetRef: 'Revelation 19:11-16',
    who: 'Authorship & Context: Joshua (or the canonical scribes of the Conquest, c. 1400–1375 BC) recorded the Christophany on the plains of Jericho before the fall of the city. The Apostle John, exiled on the Isle of Patmos under Emperor Domitian (c. AD 95–96), received the apocalyptic vision of the heavens opening to reveal the Rider on the White Horse. Identified Characters: Joshua the commander of Israel; the mysterious warrior with a drawn sword who identifies Himself as the Captain of Yahweh\'s host; heavenly armies clothed in fine linen; the kings and armies of the beast; and Jesus Christ. Christological Subject & Referent: Jesus Christ, the eternal Word of God (Ὁ Λόγος τοῦ Θεοῦ) and King of kings and Lord of lords (ΒΑΣΙΛΕΥΣ ΒΑΣΙΛΕΩΝ ΚΑΙ ΚΥΡΙΟΣ ΚΥΡΙΩΝ). In Joshua 5 He appears as an Old Testament pre-incarnate Christophany; in Revelation 19 He appears in His full apocalyptic, resurrected majesty. Redemptive Purpose: To declare that the battle for the kingdom belongs exclusively to God: Joshua must take off his shoes before the divine Commander, and all human empires must bow before the conquering Lamb.',
    what: 'The glorious Christophanic identity connecting the Captain of the LORD\'s Host in Joshua 5:13-15 ("Nay; but as captain of the host of the LORD am I now come... Loose thy shoe from off thy foot; for the place whereon thou standest is holy") to the triumphant Rider on the White Horse in Revelation 19:11-16: "And I saw heaven opened, and behold a white horse; and he that sat upon him was called Faithful and True... and his name is called The Word of God... KING OF KINGS, AND LORD OF LORDS."',
    when: 'Source Horizon: Conquest of Canaan (c. 1406 BC) on the plains of Jericho. Target Horizon: Apocalyptic Consummation revealed to John on Patmos c. AD 95–96.',
    how: 'Christophanic continuity and apocalyptic warfare. In Joshua 5:13-15, Joshua encounters a Man with a drawn sword: חַרְבּוֹ שְׁלוּפָה בְּיָדוֹ (charbo shelufah beyado — "His drawn sword in His hand"). When Joshua asks whether He is for Israel or their adversaries, He answers: לֹא כִּי אֲנִי שַׂר־צְבָא־יְהוָה עַתָּה בָאתִי (Loʾ, ki ʾani Sar-Tsevaʾ-Yahweh ʿattah vaʾti — "No, but as Commander/Captain of the army of Yahweh have I now come!"). Joshua falls with his face to the earth and worships (וַיִּשְׁתָּחוּ, vayyishtachu). An ordinary angel strictly refuses worship (Rev 19:10, 22:9), but this Captain accepts worship and commands: שַׁל־נַעַלְךָ מֵעַל רַגְלְךָ כִּי הַמָּקוֹם אֲשֶׁר אַתָּה עֹמֵד עָלָיו קֹדֶשׁ הוּא (shal-naʿalkha meʿal raglekha ki hammaqom ʾasher ʾattah ʿomed ʿalav qodesh hu — "Loose your sandal from your foot, for the place whereon you stand is holy"), the exact words spoken by Yahweh to Moses at the burning bush (Ex 3:5). In Revelation 19:11-16, John sees this identical Captain: Πιστὸς καὶ Ἀληθινός (Pistos kai Alēthinos — "Faithful and True"), who ἐν δικαιοσύνῃ κρίνει καὶ πολεμεῖ (en dikaiosynē krinei kai polemei — "in righteousness judges and makes war"). Out of His mouth goes a sharp two-edged sword (ῥομφαία ὀξεῖα, rhomphaia oxeia) to strike the nations. His eyes are as a flame of fire (ὡς φλὸξ πυρός), and He is vested with the supreme title: Βασιλεὺς βασιλέων καὶ Κύριος κυρίων (Basileus basileōn kai Kyrios kyriōn).',
    why: 'To shatter all human pride and autonomous nationalism. The Captain does not take sides in human political squabbles; He comes to take over as supreme Sovereign. Before Jericho could fall, Joshua had to surrender his command to the true King.',
    ultimatePoint: 'The Captain of the LORD\'s host who confronted Joshua at Jericho is none other than Jesus Christ, the uncreated Word of God and King of kings, who leads the heavenly armies to execute righteous judgment and establish His eternal reign.',
    personalRelevance: 'Why you need to know this: God does not exist to recruit Himself into your personal agenda, career plans, or partisan politics; He invites you to fall on your face and surrender to His holy lordship. What it does for you: It removes the crushing anxiety of having to fight life\'s spiritual battles in your own puny strength, knowing that the Commander of the armies of heaven goes before you to pull down every stronghold. Relationship with Jesus: Walking with Jesus means approaching Him not as a tame life-coach, but as the holy King of kings, joyfully taking off the shoes of self-will and following His absolute command.',
    historicalContext: {
      sourceAuthor: 'Joshua / Canonical Scribes (c. 1400–1375 BC)',
      sourceDate: 'c. 1406 BC',
      sourceSetting: 'The fortified pagan stronghold of Jericho. Israel had just crossed the Jordan River, and Joshua was surveying the impassable walls when the divine Commander appeared.',
      fulfillmentAuthor: 'Apostle John (c. AD 95–96, Patmos)',
      fulfillmentDate: 'c. AD 95–96',
      fulfillmentSetting: 'The desolate penal colony of Patmos during Domitian\'s tyrannical persecution. John receives the apocalyptic unveiling of the true Emperor of the cosmos returning in glory.',
      redemptiveBridge: 'The Captain who pulled down the walls of Jericho is the identical King of kings who will topple the kingdoms of this world and inaugurate the New Jerusalem.',
    },
  },

  // Joshua 5:13 -> Revelation 19:11-16
  'jos-5-13_Revelation 19:11-16': {
    id: 'jos-5-13_Revelation 19:11-16',
    anchorRef: 'Joshua 5:13-15',
    targetRef: 'Revelation 19:11-16',
    who: 'Authorship & Context: Joshua at Jericho; John on Patmos. Identified Characters: Joshua; the Man with the drawn sword; the heavenly armies. Christological Subject & Referent: Jesus Christ, the divine Warrior executing holy judgment. Redemptive Purpose: To reveal Christ as the righteous Conqueror of sin and rebellion.',
    what: 'The drawn sword of the Captain of the LORD\'s host in Joshua 5:13 ("with his sword drawn in his hand") pointing directly to the Rider on the White Horse whose sharp sword smites the nations in Revelation 19:11-16.',
    when: 'Source: Conquest Era (c. 1406 BC). Target: Apocalyptic Climax (c. AD 95).',
    how: 'Christophanic warfare typology. The drawn sword (חַרְבּוֹ שְׁלוּפָה, charbo shelufah) in Joshua represents immediate divine intervention. In Revelation 19:15, the sword proceeds from His mouth (ῥομφαία ὀξεῖα, rhomphaia oxeia), indicating that the Word of God Himself speaks the decree that smites the rebellious powers.',
    why: 'To demonstrate that all earthly opposition to God\'s kingdom will be vanquished by the word of Christ\'s mouth.',
    ultimatePoint: 'The drawn sword at Jericho prefigures the ultimate apocalyptic victory of Jesus Christ over every hostile power on earth.',
    personalRelevance: 'Why you need to know this: No evil, injustice, or corrupt power will stand before Christ\'s return. What it does for you: It gives you endurance in persecution, knowing that the Captain of heaven fights for His church. Relationship with Jesus: Yielding your life to Jesus as the Commander of your destiny.',
    historicalContext: {
      sourceAuthor: 'Joshua (c. 1400 BC)',
      sourceDate: 'c. 1406 BC',
      sourceSetting: 'Plains of Jericho.',
      fulfillmentAuthor: 'Apostle John (c. AD 95)',
      fulfillmentDate: 'c. AD 95',
      fulfillmentSetting: 'Patmos under Roman exile.',
      redemptiveBridge: 'From the drawn sword at Jericho to the sword of the Word of God at the Consummation.',
    },
  },

  // Joshua 5:15 -> Revelation 19:11-16
  'jos-5-15_Revelation 19:11-16': {
    id: 'jos-5-15_Revelation 19:11-16',
    anchorRef: 'Joshua 5:13-15',
    targetRef: 'Revelation 19:11-16',
    who: 'Authorship & Context: Joshua removing his shoes before Jericho; John falling at Patmos. Identified Characters: The holy Commander; Joshua; John. Christological Subject & Referent: Jesus Christ, whose presence consecrates holy ground and commands universal adoration. Redemptive Purpose: To establish the blazing holiness of Christ\'s kingdom.',
    what: 'The command to remove shoes on holy ground in Joshua 5:15 fulfilled in the divine majesty and holiness of the King of kings in Revelation 19:11-16.',
    when: 'Source: Conquest Era (c. 1406 BC). Target: Apocalyptic Climax (c. AD 95).',
    how: 'Theological continuity of divine holiness. The holy ground (קֹדֶשׁ, qodesh) in Joshua 5:15 is identical to Exodus 3:5. In Revelation 19:12, His eyes are a flame of fire (φλὸξ πυρός), burning with immaculate holiness, requiring absolute reverence and obedience.',
    why: 'To prove that the battle for God\'s kingdom is conducted in absolute holiness.',
    ultimatePoint: 'The divine Commander who demanded holy reverence from Joshua is the glorified Christ before whom every knee shall bow.',
    personalRelevance: 'Why you need to know this: God\'s presence demands reverence, awe, and holiness. What it does for you: It purges casual, irreverent familiarity from your prayer life, filling you with godly fear and holy wonder. Relationship with Jesus: Worshiping Jesus with holy awe and joyful submission.',
    historicalContext: {
      sourceAuthor: 'Joshua (c. 1400 BC)',
      sourceDate: 'c. 1406 BC',
      sourceSetting: 'Conquest camp before Jericho.',
      fulfillmentAuthor: 'Apostle John (c. AD 95)',
      fulfillmentDate: 'c. AD 95',
      fulfillmentSetting: 'Patmos vision of Christ\'s triumph.',
      redemptiveBridge: 'Holy ground in Canaan prefigures the holy New Jerusalem.',
    },
  },

  // 2 Samuel 7:12-16 -> Luke 1:32-33
  '2sa-7-12_Luke 1:32-33': {
    id: '2sa-7-12_Luke 1:32-33',
    anchorRef: '2 Samuel 7:12-16',
    targetRef: 'Luke 1:32-33',
    who: 'Authorship & Context: The Prophet Nathan delivered the unconditional Davidic Covenant oracle to King David in Jerusalem (c. 970 BC), recorded in 2 Samuel. Luke the Evangelist recorded the Annunciation of Gabriel to the virgin Mary in Nazareth (c. 4 BC), composed c. AD 60–62. Identified Characters: Yahweh the covenant Maker; the Prophet Nathan; King David; the Archangel Gabriel; the virgin Mary; the house of Jacob; and the royal seed of David. Christological Subject & Referent: Jesus Christ, the Son of the Highest (Υἱὸς Ὑψίστου) and eternal King of the Davidic line. While Solomon was an immediate, imperfect biological son who built an earthly temple, Jesus is the true divine Seed whose throne and kingdom endure without end. Redemptive Purpose: To demonstrate that the kingdom of God is an everlasting monarchy founded upon the covenant promise to David, fulfilled by the virgin-born Son of God.',
    what: 'The direct prophetic and covenantal fulfillment of the Davidic Covenant in 2 Samuel 7:12-16 ("I will set up thy seed after thee... and I will stablish the throne of his kingdom for ever") in Gabriel\'s annunciation to Mary in Luke 1:32-33: "He shall be great, and shall be called the Son of the Highest: and the Lord God shall give unto him the throne of his father David: And he shall reign over the house of Jacob for ever; and of his kingdom there shall be no end."',
    when: 'Source Horizon: Monarchy Era (c. 970 BC), Nathan speaking to David in Jerusalem. Target Horizon: The Annunciation in Nazareth (c. 4 BC), inaugurating the New Testament.',
    how: 'Prophetic covenant fulfillment and verbal precision. In 2 Samuel 7:12-16, Yahweh declares: וַהֲקִימֹתִי אֶת־זַרְעֲךָ אַחֲרֶיךָ... וְכֹנַנְתִּי אֶת־כִּסֵּא מַמְלַכְתּוֹ עַד־עוֹלָם (vahakimoti ʾet-zarʿakha ʾacharekha... vekhonanti ʾet-kisseʾ mamlakhto ʿad-ʿolam — "I will raise up your seed after you... and I will establish the throne of His kingdom forever"). God explicitly covenants a divine-human Father-Son relationship: אֲנִי אֶהְיֶה־לּוֹ לְאָב וְהוּא יִהְיֶה־לִּי לְבֵן (ʾani ʾehyeh-lo leʾav vehuʾ yihyeh-li leven — "I will be to Him a Father, and He shall be to Me a Son"). In Luke 1:32-33, Gabriel uses the exact covenant vocabulary: Οὗτος ἔσται μέγας καὶ Υἱὸς Ὑψίστου κληθήσεται (Houtos estai megas kai Huios Hypsistou klēthēsetai — "He shall be great and shall be called the Son of the Most High"), καὶ δώσει αὐτῷ Κύριος ὁ Θεὸς τὸν θρόνον Δαυὶδ τοῦ πατρὸς αὐτοῦ (kai dōsei autō Kyrios ho Theos ton thronon Dauid tou patros autou — "and the Lord God will give Him the throne of His father David"), καὶ τῆς βασιλείας αὐτοῦ οὐκ ἔσται τέλος (kai tēs basileias autou ouk estai telos — "and of His kingdom there shall be no end / no limit in time"). This proves that Jesus inherits the royal Davidic rights through Mary (and legally through Joseph, Mat 1), but reigns as the uncreated Son of the Most High.',
    why: 'To demonstrate that the collapse of the earthly Davidic monarchy during the Babylonian exile in 586 BC was not the defeat of God\'s promise. The line of David was preserved through centuries of obscurity until the true King emerged in Nazareth to reign over an indestructible kingdom.',
    ultimatePoint: 'Jesus Christ is the ultimate royal Seed of David promised in 2 Samuel 7, whose throne was established by God to reign over the house of Jacob and all nations for ever and ever.',
    personalRelevance: 'Why you need to know this: Human governments rise and collapse, politicians break promises, and earthly empires crumble into dust; the kingdom of King Jesus will never end. What it does for you: It gives you unshakable political and cosmic security, liberating you from panic over geopolitical upheavals because your citizenship is in an eternal kingdom ruled by a perfectly righteous King. Relationship with Jesus: Walking with Jesus means bending your knee to Him as your sovereign Lord and King, finding your ultimate allegiance and joy in His eternal government.',
    historicalContext: {
      sourceAuthor: 'Prophet Nathan / Gad (c. 970–930 BC)',
      sourceDate: 'c. 970 BC',
      sourceSetting: 'Jerusalem, as King David sat in his house of cedar and desired to build a temple for the Ark of God. God responded by promising to build David an enduring house/dynasty.',
      fulfillmentAuthor: 'Luke the Evangelist (c. AD 60–62, recording Gabriel c. 4 BC)',
      fulfillmentDate: 'c. 4 BC',
      fulfillmentSetting: 'The humble village of Nazareth in Galilee, where Mary, a descendant of David, was betrothed to Joseph.',
      redemptiveBridge: 'Across a millennium of royal triumphs, exilic catastrophe, and silent centuries, the covenant with David is fulfilled when the virgin conceives the King of glory.',
    },
  },

  // Psalm 110:4 -> Hebrews 7:17
  'psa-110-4_Hebrews 7:17': {
    id: 'psa-110-4_Hebrews 7:17',
    anchorRef: 'Psalm 110:4',
    targetRef: 'Hebrews 7:17',
    who: 'Authorship & Context: King David, writing under the inspiration of the Holy Spirit (c. 1000 BC), recorded Yahweh\'s irrevocable oath regarding an eternal priest-king. The author of Hebrews (c. AD 64–68) expounded this psalm to Jewish Christians who were tempted to return to the visible Levitical temple and Aaronic sacrifices in Jerusalem. Identified Characters: Yahweh making an unalterable oath; King David the prophet; Melchizedek the ancient priest-king of Salem; Aaron and the mortal Levitical priests; and Jesus Christ. Christological Subject & Referent: Jesus Christ, the royal High Priest forever after the order of Melchizedek (Σὺ ἱερεὺς εἰς τὸν αἰῶνα κατὰ τὴν τάξιν Μελχισεδέκ). He unites the royal scepter of Judah with an eternal, unchangeable priesthood. Redemptive Purpose: To prove the obsolescence and replacement of the temporary Levitical priesthood, establishing that Christ alone offers a permanent, indissoluble intercession that saves believers to the uttermost.',
    what: 'The prophetic inauguration and theological climax of the royal Melchizedekian priesthood connecting Psalm 110:4 ("The LORD hath sworn, and will not repent, Thou art a priest for ever after the order of Melchizedek") to Hebrews 7:17: "For he testifieth, Thou art a priest for ever after the order of Melchisedec."',
    when: 'Source Horizon: United Monarchy Era (c. 1000 BC) in Jerusalem. Target Horizon: Pre-AD 70 Apostolic Era (c. AD 64–68), addressing Jewish believers.',
    how: 'Rigorous grammatical and canonical exegesis. In Psalm 110:4, Yahweh confirms this appointment with an immutable covenant oath: נִשְׁבַּע יְהוָה וְלֹא יִנָּחֵם (Nishbaʿ Yahweh veloʾ yinnachem — "Yahweh has sworn and will not repent / will not change His mind"): אַתָּה־כֹהֵן לְעוֹלָם עַל־דִּבְרָתִי מַלְכִּי־צֶדֶק (ʾAttah-kohen leʿolam ʿal-dibrati Malki-tsedeq — "You are a priest forever according to the order/rank/manner of Melchizedek"). The Hebrew name מַלְכִּי־צֶדֶק combines מֶלֶךְ (melekh — king) and צֶדֶק (tsedeq — righteousness), and as king of Salem (שָׁלֵם, shalem — peace), Melchizedek was both King and Priest in Genesis 14, centuries prior to the law of Moses and the tribe of Levi. In Hebrews 7:17, the author cites this as divine testimony that Christ is a priest forever κατὰ τὴν τάξιν Μελχισεδέκ (kata tēn taxin Melchisedek — "after the order of Melchizedek"). Hebrews demonstrates that the Levitical priesthood was flawed because priests died and had to offer sacrifices for their own sins according to a fleshly commandment: κατὰ νόμον ἐντολῆς σαρκίνης (kata nomon entolēs sarkinēs). By contrast, Christ was appointed κατὰ δύναμιν ζωῆς ἀκαταλύτου (kata dynamin zōēs akatalytou — "according to the power of an indestructible / indissoluble life"). Because Christ lives forever, He possesses an unchangeable priesthood: ἀπαράβατον ἔχει τὴν ἱερωσύνην (aparabaton echei tēn hierōsynēn — a non-transferable, untransgressable priesthood), enabling Him to save to the uttermost (εἰς τὸ παντελές, eis to panteles) all who draw near to God through Him.',
    why: 'To demonstrate that Jesus did not violate the Law by becoming High Priest despite being from the tribe of Judah (not Levi). His priesthood belongs to an older, higher, royal order guaranteed by divine oath before which Aaron\'s temporary order must give way.',
    ultimatePoint: 'Jesus Christ is the eternal High Priest after the order of Melchizedek, whose resurrected, indestructible life guarantees an everlasting royal priesthood and complete, eternal salvation for all who come to God through Him.',
    personalRelevance: 'Why you need to know this: You do not need an earthly mediator, confessional booth, or mortal priest to access God; Jesus Christ lives right now to intercede for you personally before the throne. What it does for you: It gives you absolute, eternal security, knowing that whenever you stumble, Christ\'s continuous heavenly intercession preserves your standing before the Father and keeps you from falling. Relationship with Jesus: Walking with Jesus means approaching the throne of grace with bold confidence every day, knowing that your High Priest understands your weaknesses and constantly represents you in the presence of God.',
    historicalContext: {
      sourceAuthor: 'King David (c. 1000 BC)',
      sourceDate: 'c. 1000 BC',
      sourceSetting: 'Jerusalem, after David conquered the Jebusite city of Zion, meditating upon Melchizedek who had ruled that same city a millennium prior.',
      fulfillmentAuthor: 'Author of Hebrews (c. AD 64–68)',
      fulfillmentDate: 'c. AD 64–68',
      fulfillmentSetting: 'Jewish Christians in Rome/Judea tempted to revert to the Temple rituals to avoid Roman persecution and Jewish excommunication.',
      redemptiveBridge: 'Melchizedek\'s mysterious appearance in Genesis 14 is illuminated by David\'s prophecy in Psalm 110, culminating in Jesus Christ entering the heavenly Holy of Holies as our eternal High Priest.',
    },
  },

  // Psalm 110:4 -> Hebrews 5:6
  'psa-110-4_Hebrews 5:6': {
    id: 'psa-110-4_Hebrews 5:6',
    anchorRef: 'Psalm 110:4',
    targetRef: 'Hebrews 5:6',
    who: 'Authorship & Context: David\'s prophetic psalm; Hebrews author expounding Christ\'s credentials. Identified Characters: The Father who appoints; Jesus who obeys; Aaron who was called; and struggling believers. Christological Subject & Referent: Jesus Christ, appointed by the Father to eternal priesthood. Redemptive Purpose: To prove Christ did not glorify Himself, but was officially commissioned by God.',
    what: 'The Father\'s divine appointment of Christ to the Melchizedekian priesthood in Psalm 110:4 cited in Hebrews 5:6: "As he saith also in another place, Thou art a priest for ever after the order of Melchisedec."',
    when: 'Source: Monarchy Era (c. 1000 BC). Target: Apostolic Era (c. AD 64–68).',
    how: 'Exegetical appointment formula. Hebrews 5:5-6 links Psalm 2:7 ("Thou art my Son") with Psalm 110:4 ("Thou art a priest forever"). Christ did not usurp sacerdotal office (οὐχ ἑαυτὸν ἐδόξασεν γενηθῆναι ἀρχιερέα), but was formally summoned by the Father.',
    why: 'To establish that Christ\'s priesthood possesses supreme legitimacy and divine mandate.',
    ultimatePoint: 'Christ was divinely ordained by the Father as our eternal High Priest after the order of Melchizedek.',
    personalRelevance: 'Why you need to know this: Your salvation is sanctioned by the highest authority in the universe. What it does for you: Delivers from spiritual insecurity, knowing the Father Himself appointed Christ to save you. Relationship with Jesus: Trusting in Christ\'s divine appointment as your sympathetic Advocate.',
    historicalContext: {
      sourceAuthor: 'King David (c. 1000 BC)',
      sourceDate: 'c. 1000 BC',
      sourceSetting: 'Jerusalem oracle.',
      fulfillmentAuthor: 'Author of Hebrews (c. AD 64–68)',
      fulfillmentDate: 'c. AD 64–68',
      fulfillmentSetting: 'Pastoral exhortation to persecuted believers.',
      redemptiveBridge: 'The eternal decree of God establishes Christ\'s royal priesthood.',
    },
  },

  // Psalm 110:4 -> Hebrews 7:21
  'psa-110-4_Hebrews 7:21': {
    id: 'psa-110-4_Hebrews 7:21',
    anchorRef: 'Psalm 110:4',
    targetRef: 'Hebrews 7:21',
    who: 'Authorship & Context: David\'s psalm; Hebrews author contrasting Aaronic and Melchizedekian orders. Identified Characters: Yahweh swearing; Christ receiving the oath; Aaron and sons. Christological Subject & Referent: Jesus Christ, the guarantor of an irrevocable covenant. Redemptive Purpose: To show the unchangeable certainty of the New Covenant.',
    what: 'The solemn divine oath of Psalm 110:4 emphasized in Hebrews 7:21: "(For those priests were made without an oath; but this with an oath by him that said unto him, The Lord sware and will not repent, Thou art a priest for ever after the order of Melchisedec:)"',
    when: 'Source: Monarchy Era (c. 1000 BC). Target: Apostolic Era (c. AD 64–68).',
    how: 'Theological contrast of covenant ratification. Levitical priests were consecrated without a divine oath (χωρὶς ὁρκωμοσίας). Christ was established μετὰ ὁρκωμοσίας (meta horkōmosias — with the swearing of an oath by God). Therefore, Jesus has become the ἔγγυος (engyos — legal guarantor / surety) of a better covenant (κρείττονος διαθήκης).',
    why: 'To demonstrate that God\'s oath makes Christ\'s priesthood permanently irreversible.',
    ultimatePoint: 'The divine oath of Psalm 110:4 guarantees that Christ\'s priesthood and the New Covenant can never fail or be replaced.',
    personalRelevance: 'Why you need to know this: God swore by Himself that Christ\'s priesthood will never end. What it does for you: Banishes all fear of God changing His mind about your salvation. Relationship with Jesus: Rest in the eternal security of Christ\'s oath-bound priesthood.',
    historicalContext: {
      sourceAuthor: 'King David (c. 1000 BC)',
      sourceDate: 'c. 1000 BC',
      sourceSetting: 'Prophetic psalm of David.',
      fulfillmentAuthor: 'Author of Hebrews (c. AD 64–68)',
      fulfillmentDate: 'c. AD 64–68',
      fulfillmentSetting: 'Addressing Hebrew Christians.',
      redemptiveBridge: 'The unalterable oath of God guarantees our eternal redemption.',
    },
  },

  // Psalm 110:1 -> Matthew 22:44
  'psa-110-1_Matthew 22:44': {
    id: 'psa-110-1_Matthew 22:44',
    anchorRef: 'Psalm 110:1',
    targetRef: 'Matthew 22:44',
    who: 'Authorship & Context: King David composed Psalm 110 by the Holy Spirit (c. 1000 BC). Jesus Christ confronted the Pharisees in the Temple courts in Jerusalem during Passion Week (c. AD 30), recorded by the Apostle Matthew (c. AD 60–68). Identified Characters: Yahweh the Father; Adonai (David\'s Lord); King David the prophet; the Pharisees and scribes questioning Jesus; and Jesus of Nazareth. Christological Subject & Referent: Jesus Christ, who is simultaneously the biological son of David according to the flesh, and the eternal, sovereign Lord (Κύριος) of David according to His divine nature. Redemptive Purpose: To expose the reductionist Jewish expectation of the Messiah as a mere political military descendant, revealing that the true Messiah is the divine Son of God seated at the right hand of the Father.',
    what: 'The profound messianic riddle connecting Psalm 110:1 ("The LORD said unto my Lord, Sit thou at my right hand, until I make thine enemies thy footstool") to Jesus silencing the Pharisees in Matthew 22:41-46: "The LORD said unto my Lord, Sit thou on my right hand, till I make thine enemies thy footstool? If David then call him Lord, how is he his son?"',
    when: 'Source Horizon: United Monarchy Era (c. 1000 BC) in Jerusalem. Target Horizon: Passion Week in Jerusalem c. AD 30, recorded c. AD 60–68.',
    how: 'Grammatical interrogation and theological deduction. In Psalm 110:1, David writes: נְאֻם יְהוָה לַאדֹנִי שֵׁב לִימִינִי עַד־אָשִׁית אֹיְבֶיךָ הֲדֹם לְרַגְלֶיךָ (Ne\'um Yahweh la-Adoni: Shev li-mini ʿad-ʾashit ʾoyvekha hadom le-raglekha — "The oracle of Yahweh to my Lord [ʾAdoni]: Sit at My right hand until I make your enemies a footstool for your feet"). In ancient Near Eastern patriarchal culture, no father or grandfather ever addressed his son or descendant as "my Lord" (אֲדֹנִי); the superior always addresses the inferior. Jesus poses the devastating dilemma in Greek: Εἶπεν Κύριος τῷ Κυρίῳ μου (Eipen Kyrios tō Kyriō mou): Εἰ οὖν Δαυὶδ καλεῖ αὐτὸν Κύριον, πῶς υἱὸς αὐτοῦ ἐστιν; ("If David then calls Him \'Lord\', how is He his son?"). The Pharisees could not answer a word. The only theological resolution is the Incarnation: the Messiah is David\'s son through human lineage (Luke 1:32, Rom 1:3), but David\'s eternal Lord by uncreated divine nature (Rom 1:4, 9:5), seated at the supreme place of cosmic dominion.',
    why: 'To demonstrate that the Messiah is not merely a second David who will establish an earthly geopolitical kingdom, but the sovereign Creator-God whose enthronement at the right hand of the Father conquers death, sin, and all cosmic enemies.',
    ultimatePoint: 'Jesus Christ is David\'s son by human descent and David\'s eternal Lord by divine nature, reigning at the right hand of the Father until every enemy is subdued beneath His feet.',
    personalRelevance: 'Why you need to know this: Jesus is not merely a good human teacher, historical prophet, or moral exemplar; He is the sovereign Lord of all reality before whom every knee must bow. What it does for you: It gives you supreme confidence that all demonic powers, worldly opposition, and personal adversaries are already doomed to be placed under Christ\'s feet. Relationship with Jesus: Submitting to Jesus not as a casual friend, but as your absolute sovereign Lord, delighting to serve His kingdom with your whole heart.',
    historicalContext: {
      sourceAuthor: 'King David (c. 1000 BC)',
      sourceDate: 'c. 1000 BC',
      sourceSetting: 'Jerusalem, as David contemplates the cosmic reign of the coming Messiah.',
      fulfillmentAuthor: 'Apostle Matthew (c. AD 60–68, recording Jesus c. AD 30)',
      fulfillmentDate: 'c. AD 30',
      fulfillmentSetting: 'The Temple courts in Jerusalem on Tuesday of Passion Week, surrounded by hostile religious leaders trying to entrap Him.',
      redemptiveBridge: 'From David\'s prophetic vision of the enthroned Lord to Jesus asserting His divine sonship in the Temple, culminating in His ascension to the right hand of the Father.',
    },
  },

  // Psalm 110:1 -> Acts 2:34-35
  'psa-110-1_Acts 2:34-35': {
    id: 'psa-110-1_Acts 2:34-35',
    anchorRef: 'Psalm 110:1',
    targetRef: 'Acts 2:34-35',
    who: 'Authorship & Context: King David wrote Psalm 110. The Apostle Peter, filled with the Holy Spirit on the Day of Pentecost (c. AD 30), proclaimed this psalm to thousands of Jews gathered in Jerusalem, recorded by Luke in Acts (c. AD 62–64). Identified Characters: God the Father; Jesus the resurrected Messiah; King David whose tomb was in Jerusalem; the Apostle Peter and the Eleven; and the crowd at Pentecost. Christological Subject & Referent: The resurrected and ascended Jesus of Nazareth, whom God made both Lord and Christ (Κύριον καὶ Χριστόν). Redemptive Purpose: To prove that Jesus\' resurrection and ascension fulfill David\'s prophecy, authenticating the outpouring of the Holy Spirit.',
    what: 'The apostolic citation of Psalm 110:1 in Peter\'s Pentecost sermon in Acts 2:34-36: "For David is not ascended into the heavens: but he saith himself, The LORD said unto my Lord, Sit thou on my right hand, Until I make thy foes thy footstool. Therefore let all the house of Israel know assuredly, that God hath made that same Jesus, whom ye have crucified, both Lord and Christ."',
    when: 'Source: Monarchy Era (c. 1000 BC). Target: Day of Pentecost (c. AD 30) in Jerusalem.',
    how: 'Historical-grammatical and apostolic resurrection hermeneutics. Peter argues that David died, was buried, and his tomb remains in Jerusalem (οὐ γὰρ Δαυὶδ ἀνέβη εἰς τοὺς οὐρανούς, "for David did not ascend into the heavens"). Therefore, Psalm 110:1 cannot refer to David. It refers exclusively to the resurrected Jesus, whom God exalted to His right hand (τῇ δεξιᾷ οὖν τοῦ Θεοῦ ὑψωθείς), who received the promised Holy Spirit from the Father and poured it out upon the church. Peter reaches the triumphant climax: Κύριον αὐτὸν καὶ Χριστὸν ἐποίησεν ὁ Θεός ("God has made Him both Lord and Christ, this Jesus whom you crucified!").',
    why: 'To demonstrate that the cross was not a tragic defeat, but the path to cosmic enthronement. The very One whom Jerusalem rejected has been crowned King of kings at the right hand of God.',
    ultimatePoint: 'The ascension of the resurrected Jesus to the right hand of the Father fulfills Psalm 110:1, proving that Jesus is the enthroned Lord and Messiah who pours out the Holy Spirit upon His people.',
    personalRelevance: 'Why you need to know this: The Holy Spirit living inside you is the direct proof that Jesus Christ is currently reigning at the right hand of God in supreme majesty. What it does for you: It fills you with boldness and evangelistic power, knowing that the resurrected King is actively advancing His kingdom across the earth through His church. Relationship with Jesus: Walking with Jesus as your ascended King, receiving His Holy Spirit daily to empower your witness and sanctify your life.',
    historicalContext: {
      sourceAuthor: 'King David (c. 1000 BC)',
      sourceDate: 'c. 1000 BC',
      sourceSetting: 'David\'s court in Jerusalem.',
      fulfillmentAuthor: 'Luke the Evangelist (c. AD 62–64, recording Peter c. AD 30)',
      fulfillmentDate: 'c. AD 30',
      fulfillmentSetting: 'The Temple mount in Jerusalem on the morning of Pentecost, as the sound of rushing wind and tongues of fire drew vast crowds.',
      redemptiveBridge: 'David\'s prophecy bridges to the historical ascension of Jesus, releasing the age of the Holy Spirit.',
    },
  },

  // Isaiah 53:5 -> 1 Peter 2:24
  'isa-53-5_1 Peter 2:24': {
    id: 'isa-53-5_1 Peter 2:24',
    anchorRef: 'Isaiah 53:5',
    targetRef: '1 Peter 2:24',
    who: 'Authorship & Context: The Prophet Isaiah prophesied in Jerusalem during the reigns of Uzziah, Jotham, Ahaz, and Hezekiah (c. 740–680 BC), penning the Fourth Servant Song under the inspiration of the Spirit of Christ (1 Pet 1:11). The Apostle Peter, writing from Rome (c. AD 64–65) as an eyewitness of Christ\'s sufferings, exhorted Christian servants and believers suffering unjustly under pagan masters. Identified Characters: Yahweh laying iniquity on His Servant; the suffering Servant (Eved Yahweh); sinful, wandering sheep (humanity); Roman crucifiers and abusive masters; and redeemed believers. Christological Subject & Referent: Jesus Christ, the sinless Suffering Servant who bore our sins in His own body on the tree (ὃς τὰς ἁμαρτίας ἡμῶν αὐτὸς ἀνήνεγκεν ἐν τῷ σώματι αὐτοῦ ἐπὶ τὸ ξύλον). Redemptive Purpose: To unveil the heart of substitutionary penal atonement: Christ suffered the physical, moral, and judicial curse of our sins so that we might die to sin and live to righteousness.',
    what: 'The foundational substitutionary atonement prophecy of Isaiah 53:5 ("But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed") fulfilled in 1 Peter 2:24: "Who his own self bare our sins in his own body on the tree, that we, being dead to sins, should live unto righteousness: by whose stripes ye were healed."',
    when: 'Source Horizon: Divided Monarchy / Pre-Exilic Era (c. 700 BC) in Jerusalem. Target Horizon: Mid-1st Century Apostolic Era (c. AD 64–65) in Rome.',
    how: 'Penal substitutionary exegesis and precise linguistic fulfillment. In Isaiah 53:5, the Hebrew vocabulary depicts violent, vicarious punishment: וְהוּא מְחֹלָל מִפְּשָׁעֵנוּ מְדֻכָּא מֵעֲו‍ֹנֹתֵינוּ מוּסַר שְׁלוֹמֵנוּ עָלָיו וּבַחֲבֻרָתוֹ נִרְפָּא־לָנוּ (Vehu mecholal mippeshaʿenu, medukka meʿawonotenu, musar shelomenu ʿalav, uvachavurato nirpaʾ-lanu). The participle מְחֹלָל (mecholal, Poal of chalal) means "pierced through, mortally perforated" (anticipating the nails and spear of crucifixion); מְדֻכָּא (medukka, Pual of dakaʾ) means "pulverized, crushed under divine weight"; מוּסַר שְׁלוֹמֵנוּ (musar shelomenu) denotes the judicial chastisement that procured our peace with God; and חַבּוּרָה (chabburah) is a bloody blow-mark or stripe from a lash. In 1 Peter 2:24, Peter applies this with sacrificial precision: ὃς τὰς ἁμαρτίας ἡμῶν αὐτὸς ἀνήνεγκεν (hos tas hamartias hēmōn autos anēnegken — "Who Himself carried up / bore our sins"). The verb ἀναφέρω (anapherō) is the technical Levitical term for carrying a sacrificial animal up to the altar of God. The altar here is ἐπὶ τὸ ξύλον (epi to xylon — "upon the tree"), invoking Deuteronomy 21:23: "cursed is everyone who hangs on a tree". Peter concludes: οὗ τῷ μώλωπι ἰάθητε (hou tō mōlōpi iathēte — "by whose wound/stripe you were healed"), shifting Isaiah\'s future expectation into an accomplished, past-tense reality for all believers.',
    why: 'To demonstrate that our salvation required a genuine, physical, substitutionary bearing of the wrath of God against sin. Christ was not a mere moral example; He was the Lamb upon whom our specific guilt was imputed and executed, so that we might be delivered from both the penalty and power of sin.',
    ultimatePoint: 'Jesus Christ fulfilled Isaiah 53:5 by bearing our sins in His own body on the cross, taking the violent blow of divine judgment due to our transgressions so that we might receive eternal reconciliation and spiritual healing.',
    personalRelevance: 'Why you need to know this: You can never pay God back for your sins, nor can you cleanse your own guilt through self-punishment or moral striving; Christ bore every single one of your sins on the tree. What it does for you: It imparts profound, healing peace to your soul, shattering condemnation and giving you the power to break free from habitual sin and live righteously. Relationship with Jesus: Loving Jesus with deep, emotional tenderness, remembering that every nail, thorn, and stripe He endured was borne out of personal love for you.',
    historicalContext: {
      sourceAuthor: 'Prophet Isaiah (c. 740–680 BC)',
      sourceDate: 'c. 700 BC',
      sourceSetting: 'Jerusalem facing Assyrian threats, looking ahead to the Babylonian exile and the ultimate spiritual redemption through Yahweh\'s Servant.',
      fulfillmentAuthor: 'Apostle Peter (c. AD 64–65, Rome)',
      fulfillmentDate: 'c. AD 64–65',
      fulfillmentSetting: 'Rome, writing to household slaves and persecuted believers who suffered unjust beatings, reminding them of the sinless Servant who suffered for them.',
      redemptiveBridge: 'Isaiah\'s vision of the wounded Servant bridges seven centuries directly to Golgotha, where Christ paid the penalty for human iniquity.',
    },
  },

  // Jeremiah 31:31 -> Hebrews 8:8
  'jer-31-31_Hebrews 8:8': {
    id: 'jer-31-31_Hebrews 8:8',
    anchorRef: 'Jeremiah 31:31',
    targetRef: 'Hebrews 8:8',
    who: 'Authorship & Context: The Prophet Jeremiah prophesied in Jerusalem amidst the siege and destruction of the city by Babylon (c. 586 BC), receiving the promise of the New Covenant while imprisoned in the court of the guard (Jer 31–33). The author of Hebrews (c. AD 64–68) quoted Jeremiah 31 at length to prove that the Mosaic Old Covenant was designed from its inception to be temporary and has now been superseded by the New Covenant. Identified Characters: Yahweh the faithful covenant Lord; the Prophet Jeremiah; the house of Israel and the house of Judah; Moses and the Exodus generation who broke the Sinai covenant; and all New Covenant believers. Christological Subject & Referent: Jesus Christ, the Mediator of a better covenant (κρείττονος διαθήκης μεσίτης, Heb 8:6). He ratifies the New Covenant through His own blood. Redemptive Purpose: To transition the people of God from external shadows (stone tablets, animal sacrifices, mortal priests) into the internal, permanent reality of heart-regeneration and total forgiveness of sins.',
    what: 'The prophetic promise of the New Covenant in Jeremiah 31:31 ("Behold, the days come, saith the LORD, that I will make a new covenant with the house of Israel, and with the house of Judah") fulfilled in Hebrews 8:8: "For finding fault with them, he saith, Behold, the days come, saith the Lord, when I will make a new covenant with the house of Israel and with the house of Judah."',
    when: 'Source Horizon: Exilic Crisis Era (c. 586 BC) in besieged Jerusalem. Target Horizon: Apostolic Era (c. AD 64–68), immediately prior to the destruction of the Second Temple.',
    how: 'Covenantal theology and semantic analysis. In Jeremiah 31:31, God promises: וְכָרַתִּי אֶת־בֵּית יִשְׂרָאֵל וְאֶת־בֵּית יְהוּדָה בְּרִית חֲדָשָׁה (vekharatti ʾet-beyt Yisraʾel veʾet-beyt Yehudah berit chadashah — "and I will cut [כָּרַת, karat — to cut a covenant by sacrificial blood] with the house of Israel and with the house of Judah a New Covenant"). The covenant is חֲדָשָׁה (chadashah — entirely fresh in quality and substance, not a mere patch on the old). In Hebrews 8:8, the author translates this as διαθήκην καινήν (diathēkēn kainēn — a covenant new in quality and nature, distinct from véos which is merely recent in time). Hebrews points out that God found fault not with His holy law, but "with them" (μεμφόμενος γὰρ αὐτοὺς λέγει) because fallen human nature could not keep the Sinai terms. The New Covenant solves this by internalizing the law: διδοὺς νόμους μου εἰς τὴν διάνοιαν αὐτῶν, καὶ ἐπὶ καρδίας αὐτῶν ἐπιγράψω αὐτούς ("I will put My laws into their minds, and write them upon their hearts"), sealed with unconditional grace: "their sins and their iniquities will I remember no more" (Heb 8:12). Hebrews concludes in verse 13: "In that he saith, A new covenant, he hath made the first old. Now that which decayeth and waxeth old is ready to vanish away."',
    why: 'To demonstrate that the cessation of the Mosaic ceremonial law was not an act of apostolic rebellion, but the explicit plan of God foretold by Jeremiah six centuries earlier. The old covenant was a temporary tutor; the New Covenant in Christ is eternal.',
    ultimatePoint: 'Jesus Christ has mediated and ratified the New Covenant foretold by Jeremiah, transforming human hearts through the Holy Spirit and granting eternal remission of sins through His atoning sacrifice.',
    personalRelevance: 'Why you need to know this: You are not under a legalistic contract of works where one failure disqualifies you; you are in a permanent covenant of grace with God written on your heart. What it does for you: It gives you a supernatural desire to love and obey God from the inside out, while providing absolute peace that your sins are permanently forgiven and forgotten by the Father. Relationship with Jesus: Living in the intimate communion of the New Covenant, where Jesus Himself writes His desires upon your heart and walks with you as your faithful Savior.',
    historicalContext: {
      sourceAuthor: 'Prophet Jeremiah (c. 627–580 BC)',
      sourceDate: 'c. 586 BC',
      sourceSetting: 'Jerusalem falling to Nebuchadnezzar\'s army, the temple burning, and the Davidic monarchy seemingly extinguished. Jeremiah prophesies of an unshakeable future covenant.',
      fulfillmentAuthor: 'Author of Hebrews (c. AD 64–68)',
      fulfillmentDate: 'c. AD 64–68',
      fulfillmentSetting: 'Jewish Christians clinging to the earthly Temple rituals in Jerusalem. Hebrews announces that the Temple system is ready to vanish away (fulfilled in AD 70).',
      redemptiveBridge: 'From the broken covenant at Sinai to the promise in the ruins of Jerusalem, culminating in the upper room and the cross where Jesus inaugurated the New Covenant.',
    },
  },

  // Jeremiah 31:31 -> Hebrews 10:16
  'jer-31-31_Hebrews 10:16': {
    id: 'jer-31-31_Hebrews 10:16',
    anchorRef: 'Jeremiah 31:31',
    targetRef: 'Hebrews 10:16',
    who: 'Authorship & Context: Jeremiah; Hebrews author. Identified Characters: The Holy Spirit witnessing; the covenant community. Christological Subject & Referent: Jesus, whose one sacrifice perfected forever those who are sanctified. Redemptive Purpose: To establish that the repetition of animal sacrifices is obsolete because Christ\'s one offering brings total remission.',
    what: 'The Holy Spirit\'s testimony to the New Covenant in Jeremiah 31 cited in Hebrews 10:16: "This is the covenant that I will make with them after those days, saith the Lord, I will put my laws into their hearts, and in their minds will I write them; And their sins and iniquities will I remember no more."',
    when: 'Source: Exilic Crisis (c. 586 BC). Target: Apostolic Era (c. AD 64–68).',
    how: 'Theological correlation of sacrifice and covenant. In Hebrews 10:14-18, the author demonstrates that animal sacrifices could never take away sins because they were offered year by year continually. But Christ offered μίαν ὑπὲρ ἁμαρτιῶν θυσίαν εἰς τὸ διηνεκές ("one sacrifice for sins forever"). The Holy Spirit confirms this by quoting Jeremiah 31:33-34: where there is remission of these, there is no more offering for sin (ὅπου δὲ ἄφεσις τούτων, οὐκέτι προσφορὰ περὶ ἁμαρτίας).',
    why: 'To prove that true forgiveness is complete and final; no further sacrificial system is required.',
    ultimatePoint: 'Christ\'s once-for-all sacrifice fulfilled Jeremiah\'s New Covenant, providing total remission of sins and internal heart transformation.',
    personalRelevance: 'Why you need to know this: Your sins are not merely covered temporarily; they are permanently erased from God\'s record. What it does for you: Delivers your conscience from dead works and lingering guilt, enabling you to enter the Holy of Holies with full assurance. Relationship with Jesus: Walking in joyful fellowship with Jesus without fear of rejection.',
    historicalContext: {
      sourceAuthor: 'Prophet Jeremiah (c. 586 BC)',
      sourceDate: 'c. 586 BC',
      sourceSetting: 'Ruins of Jerusalem.',
      fulfillmentAuthor: 'Author of Hebrews (c. AD 64–68)',
      fulfillmentDate: 'c. AD 64–68',
      fulfillmentSetting: 'Instructing Hebrew Christians.',
      redemptiveBridge: 'Christ\'s one sacrifice fulfills the promise of complete heart renewal and pardon.',
    },
  },

  // Jeremiah 31:31 -> Luke 22:20
  'jer-31-31_Luke 22:20': {
    id: 'jer-31-31_Luke 22:20',
    anchorRef: 'Jeremiah 31:31',
    targetRef: 'Luke 22:20',
    who: 'Authorship & Context: The Prophet Jeremiah; Luke the Evangelist recording Jesus in the Upper Room in Jerusalem on the night of His betrayal (c. AD 30). Identified Characters: Jesus the Lord; the Twelve Apostles; Judas the betrayer; and Jeremiah the prophet. Christological Subject & Referent: Jesus Christ, who in His own person and shed blood enacts and ratifies the New Covenant. Redemptive Purpose: To transform the ancient Passover feast into the Lord\'s Supper, showing that the New Covenant is purchased by His blood.',
    what: 'The historical inauguration of Jeremiah\'s New Covenant in Jesus\' words at the Last Supper in Luke 22:20: "Likewise also the cup after supper, saying, This cup is the new testament in my blood, which is shed for you."',
    when: 'Source: Exilic Crisis (c. 586 BC). Target: Passion Week (c. AD 30) in the Upper Room.',
    how: 'Covenant inauguration formula. At Mount Sinai, Moses took the blood of oxen and sprinkled the people, saying: "Behold the blood of the covenant" (Ex 24:8). In the Upper Room, Jesus takes the cup of wine after the Passover meal and proclaims: Τοῦτο τὸ ποτήριον ἡ καινὴ διαθήκη ἐν τῷ αἵματί μου, τὸ ὑπὲρ ὑμῶν ἐκχυννόμενον (Touto to potērion hē kainē diathēkē en tō haimati mou, to hyper hymōn ekchynnomenon — "This cup is the new covenant in My blood, which is poured out for you"). Jesus explicitly unites Jeremiah\'s בְּרִית חֲדָשָׁה (berit chadashah / ἡ καινὴ διαθήκη) with His own impending death on Calvary. The New Covenant is not inaugurated with the blood of bulls and goats, but with the blood of the Son of God poured out for the remission of sins.',
    why: 'To declare to the disciples and to the world that Jeremiah\'s covenant promise was officially being born that very night through Christ\'s sacrificial death.',
    ultimatePoint: 'Jesus Christ inaugurated the New Covenant foretold by Jeremiah at the Last Supper, sealing it the next morning with His own blood upon the cross.',
    personalRelevance: 'Why you need to know this: Every time you partake of the Lord\'s Supper, you are celebrating the New Covenant that Jesus personally bought for you with His own blood. What it does for you: It anchors your daily life in covenant certainty, knowing that God\'s promises to you are sealed in the shed blood of Jesus. Relationship with Jesus: Remembering His sacrifice with tender love and living in vital communion with Him as your covenant Lord.',
    historicalContext: {
      sourceAuthor: 'Prophet Jeremiah (c. 586 BC)',
      sourceDate: 'c. 586 BC',
      sourceSetting: 'Jerusalem under siege.',
      fulfillmentAuthor: 'Luke the Evangelist (c. AD 60–62, recording Jesus c. AD 30)',
      fulfillmentDate: 'c. AD 30',
      fulfillmentSetting: 'The Upper Room in Jerusalem on Passover night.',
      redemptiveBridge: 'From the prophetic tears of Jeremiah to the communion cup of Jesus, the New Covenant becomes historical reality.',
    },
  },

  // Daniel 7:13-14 -> Matthew 26:64 / Revelation 1:7
  'dan-7-13_Matthew 26:64 / Revelation 1:7': {
    id: 'dan-7-13_Matthew 26:64 / Revelation 1:7',
    anchorRef: 'Daniel 7:13-14',
    targetRef: 'Matthew 26:64 / Revelation 1:7',
    who: 'Authorship & Context: The Prophet Daniel received apocalyptic visions while exiled in Babylon during the reign of Belshazzar (c. 553 BC). Jesus Christ stood before the Sanhedrin and High Priest Caiaphas in Jerusalem on the night of His trial (c. AD 30), recorded by Matthew. The Apostle John beheld the glorified Son of Man on Patmos (c. AD 95). Identified Characters: The Ancient of Days (God the Father); the Son of Man (Christ); angelic thousands ministering; the beasts representing pagan world empires; Caiaphas the High Priest; the Sanhedrin; and all nations, peoples, and languages. Christological Subject & Referent: Jesus Christ, the divine Son of Man (ὁ Υἱὸς τοῦ ἀνθρώπου / כְּבַר אֱנָשׁ). He rides the clouds of heaven, receives an everlasting dominion, and will return visibly to judge the earth. Redemptive Purpose: To expose the illegitimacy of earthly human courts condemning Christ, showing that the condemned Prisoner will soon sit on the supreme throne of the cosmos as universal Judge and King.',
    what: 'The climactic messianic vision of the Son of Man in Daniel 7:13-14 ("behold, one like the Son of man came with the clouds of heaven, and came to the Ancient of days... And there was given him dominion, and glory, and a kingdom") fulfilled in Jesus\' solemn trial confession in Matthew 26:64 ("Hereafter shall ye see the Son of man sitting on the right hand of power, and coming in the clouds of heaven") and John\'s apocalyptic prophecy in Revelation 1:7 ("Behold, he cometh with clouds; and every eye shall see him").',
    when: 'Source Horizon: Neo-Babylonian Era (c. 553 BC) in Babylon. Target Horizon: AD 30 trial in Jerusalem, and the apocalyptic Second Coming.',
    how: 'Aramaic apocalyptic exegesis and messianic self-identification. In Daniel 7:13-14, the Aramaic text records: וַאֲרוּ עִם־עֲנָנֵי שְׁמַיָּא כְּבַר אֱנָשׁ אָתֵה הֲוָה וְעַד־עַתִּיק יֽוֹמַיָּא מְטָה (vaʾaru ʿim-ʿananey shemayya kevar ʾenash ʾateh havah, veʿad-ʿAttiq yomayya metah — "and behold, with the clouds of heaven One like a Son of Man was coming, and He reached the Ancient of Days"). In the Old Testament, riding the clouds is the exclusive prerogative of Yahweh (Psa 104:3, Isa 19:1). Furthermore, this Son of Man receives שָׁלְטָן עָלַם (sholtan ʿalam — an everlasting dominion) and all nations serve/worship Him: יִפְלְחוּן (yiplechun, from pelach — sacrificial divine worship reserved exclusively for God). When the High Priest Caiaphas adjured Jesus by the living God to declare if He was the Christ, Jesus replied: Πλὴν λέγω ὑμῖν, ἀπ\' ἄρτι ὄψεσθε τὸν Υἱὸν τοῦ ἀνθρώπου καθήμενον ἐκ δεξιῶν τῆς δυνάμεως καὶ ἐρχόμενον ἐπὶ τῶν νεφελῶν τοῦ οὐρανοῦ (Plēn legō hymin, ap\' arti opsesthe ton Huion tou anthrōpou kathēmenon ek dexiōn tēs dynameōs kai erchomenon epi tōn nephelōn tou ouranou — "Nevertheless I say to you, Hereafter you shall see the Son of Man sitting at the right hand of Power and coming on the clouds of heaven"). The High Priest immediately tore his robes and cried "Blasphemy!", fully understanding that Jesus was claiming Daniel 7:13—asserting His uncreated deity and supreme cosmic judgeship. John confirms this in Revelation 1:7: Ἰδοὺ ἔρχεται μετὰ τῶν νεφελῶν, καὶ ὄψεται αὐτὸν πᾶς ὀφθαλμός ("Behold, He is coming with the clouds, and every eye will see Him").',
    why: 'To reveal that Jesus\' favorite title for Himself—"the Son of Man"—was not merely a claim to human frailty, but the code-name for the divine, cloud-riding Sovereign of Daniel 7 who inherits the cosmos.',
    ultimatePoint: 'Jesus Christ is the divine Son of Man of Daniel 7, who receives an everlasting dominion from the Father and will return in glory on the clouds of heaven to judge all nations and establish His eternal kingdom.',
    personalRelevance: 'Why you need to know this: The humble Jesus who was spit upon and mocked in Jerusalem is the very King who will appear in blazing majesty on the clouds to judge history. What it does for you: It gives you fearless courage when standing before hostile worldly cultures or courts, knowing that your Lord holds supreme jurisdiction over all judges, presidents, and kings. Relationship with Jesus: Bowing before Jesus as your glorified King and living with joyful anticipation for the day He returns on the clouds.',
    historicalContext: {
      sourceAuthor: 'Prophet Daniel (c. 605–530 BC)',
      sourceDate: 'c. 553 BC',
      sourceSetting: 'Babylon, as pagan empires (Babylon, Medo-Persia, Greece, Rome) arise as violent beasts from the stormy sea. Daniel is shown the heavenly courtroom where the Son of Man destroys the beasts.',
      fulfillmentAuthor: 'Apostle Matthew (c. AD 60–68) & Apostle John (c. AD 95)',
      fulfillmentDate: 'c. AD 30 / AD 95',
      fulfillmentSetting: 'The nocturnal trial before the Sanhedrin in Jerusalem, and John\'s exile on Patmos.',
      redemptiveBridge: 'Daniel\'s heavenly courtroom vision culminates in Jesus\' confession at His trial, guaranteeing His universal return as triumphant King.',
    },
  },

  // Zechariah 12:10 -> John 19:37
  'zec-12-10_John 19:37': {
    id: 'zec-12-10_John 19:37',
    anchorRef: 'Zechariah 12:10',
    targetRef: 'John 19:37',
    who: 'Authorship & Context: The Prophet Zechariah prophesied in post-exilic Jerusalem during the rebuilding of the Second Temple (c. 520–480 BC). The Apostle John stood at the foot of the cross on Golgotha as an eyewitness (c. AD 30/33), recording this fulfillment in his Gospel (c. AD 85–95). Identified Characters: Yahweh the speaker; the house of David and the inhabitants of Jerusalem; the Roman soldier who pierced Jesus\' side with a spear; the Apostle John bearing witness; and Jesus Christ. Christological Subject & Referent: Jesus Christ, who is Yahweh incarnate. In Zechariah, Yahweh says "they shall look upon ME whom they have pierced"; on the cross, the side of Jesus is pierced, proving that the One pierced on the tree is God Himself in human flesh. Redemptive Purpose: To unveil the profound mystery of the pierced Shepherd-God: God took on human flesh so that He might be pierced for our sins, opening a fountain of grace and cleansing for all who repent.',
    what: 'The staggering prophetic fulfillment connecting Zechariah 12:10 ("and they shall look upon me whom they have pierced, and they shall mourn for him, as one mourneth for his only son") to the piercing of Jesus\' side in John 19:37: "And again another scripture saith, They shall look on him whom they pierced."',
    when: 'Source Horizon: Post-Exilic Restoration Era (c. 520 BC) in Jerusalem. Target Horizon: Good Friday at Golgotha outside Jerusalem c. AD 30/33.',
    how: 'Theological, grammatical, and canonical exegesis. In Zechariah 12:10, Yahweh Himself is the grammatical first-person speaker throughout the chapter. He proclaims: וְשָׁפַכְתִּי עַל־בֵּית דָּוִיד וְעַל יוֹשֵׁב יְרוּשָׁלִַם רוּחַ חֵן וְתַחֲנוּנִים וְהִבִּיטוּ אֵלַי אֵת אֲשֶׁר־דָּקָרוּ וְסָפְדוּ עָלָיו כְּמִסְפֵּד עַל־הַיָּחִיד (Veshafakhti ʿal-beyt David veʿal yoshev Yerushalayim ruach chen vetachanunim, vehibbitu ʾelay ʾet ʾasher-daqaru, vesafedu ʿalav kemisped ʿal-hayyachid — "And I will pour out on the house of David and on the inhabitants of Jerusalem the Spirit of grace [חֵן, chen] and supplication [תַּחֲנוּנִים, tachanunim]; and they will look upon ME [אֵלַי, ʾelay] whom they have PIERCED [דָּקָרוּ, daqaru], and they will mourn for Him as one mourns for an only son [הַיָּחִיד, hayyachid]"). The verb דָּקַר (daqar) denotes literal, violent piercing with a spear, lance, or sword. In John 19:34, a Roman soldier pierced Jesus\' side with a lance (λόγχῃ αὐτοῦ τὴν πλευρὰν ἔνυξεν), and immediately came out blood and water. In verse 37, John quotes Zechariah: Ὄψονται εἰς ὃν ἐξεκέντησαν (Opsontai eis hon exekentēsan — "They shall look on Him whom they pierced"). John uses the verb ἐκκεντέω (ekkenteō — to pierce through), deliberately correcting the Greek Septuagint translation which had softened the reading. John identifies the pierced Jesus as the very Yahweh of Zechariah 12:10.',
    why: 'To demonstrate the unfathomable humility and love of God: the sovereign Lord of the universe allowed Himself to be pierced by the creatures He made, turning the wound of crucifixion into the fountain of eternal cleansing from sin and uncleanness (Zec 13:1).',
    ultimatePoint: 'Jesus Christ is Yahweh in the flesh: on the cross He was literally pierced for our redemption, so that looking upon Him in faith and repentance brings the outpouring of the Spirit of grace and eternal pardon.',
    personalRelevance: 'Why you need to know this: Your sins pierced the Son of God; the wounds on Jesus\' hands, feet, and side are the permanent measure of what it cost God to redeem you. What it does for you: It melts a hard, rebellious heart into tender, loving repentance, assuring you that the fountain opened in Jesus\' pierced side washes away every stain of guilt and shame. Relationship with Jesus: Gazing upon the pierced Savior with brokenhearted worship, thanking Him that His wounds are your healing and His pierced side is your refuge.',
    historicalContext: {
      sourceAuthor: 'Prophet Zechariah (c. 520–480 BC)',
      sourceDate: 'c. 520 BC',
      sourceSetting: 'Post-exilic Jerusalem, as a small, impoverished remnant of Jews struggled to rebuild the Temple amidst Persian imperial domination. Zechariah looks beyond their poverty to the eschatological redemption of Zion.',
      fulfillmentAuthor: 'Apostle John (c. AD 85–95, eyewitness c. AD 30/33)',
      fulfillmentDate: 'c. AD 30/33',
      fulfillmentSetting: 'The hill of Golgotha at twilight on Good Friday, as blood and water flowed from Jesus\' pierced side.',
      redemptiveBridge: 'The pierced Shepherd-God of Zechariah 12 bridges from post-exilic prophetic longing to Calvary, and forward to the Second Coming when every tribe of the earth shall mourn.',
    },
  },

  // Zechariah 12:10 -> Revelation 1:7
  'zec-12-10_Revelation 1:7': {
    id: 'zec-12-10_Revelation 1:7',
    anchorRef: 'Zechariah 12:10',
    targetRef: 'Revelation 1:7',
    who: 'Authorship & Context: Zechariah; John on Patmos. Identified Characters: The pierced Lord returning; every eye; those who pierced Him; and all tribes of the earth. Christological Subject & Referent: Jesus Christ returning as the pierced Sovereign. Redemptive Purpose: To reveal the global consummation of Zechariah\'s prophecy at the Second Coming.',
    what: 'The eschatological fulfillment of Zechariah 12:10 in Revelation 1:7: "Behold, he cometh with clouds; and every eye shall see him, and they also which pierced him: and all kindreds of the earth shall wail because of him. Even so, Amen."',
    when: 'Source: Post-Exilic Era (c. 520 BC). Target: Apocalyptic Climax (c. AD 95).',
    how: 'Apocalyptic universalization. John combines Daniel 7:13 ("cometh with clouds") with Zechariah 12:10: καὶ ὄψεται αὐτὸν πᾶς ὀφθαλμὸς καὶ οἵτινες αὐτὸν ἐξεκέντησαν, καὶ κόψονται ἐπ\' αὐτὸν πᾶσαι αἱ φυλαὶ τῆς γῆς ("and every eye will see Him, and those who pierced Him, and all the tribes of the earth will mourn over Him"). The mourning of Zechariah 12 becomes global at Christ\'s visible return.',
    why: 'To demonstrate that the rejected, pierced Savior will be vindicated before the eyes of all humanity.',
    ultimatePoint: 'The One who was pierced on Calvary will return in the clouds as universal Judge, and every eye will see Him.',
    personalRelevance: 'Why you need to know this: History is moving toward a decisive day when all denial of Christ will end. What it does for you: Inspires urgency in sharing the gospel, that men and women may look to Him in saving faith now before they must face Him in judgment. Relationship with Jesus: Longing for His appearing with holy expectation.',
    historicalContext: {
      sourceAuthor: 'Prophet Zechariah (c. 520 BC)',
      sourceDate: 'c. 520 BC',
      sourceSetting: 'Post-exilic Jerusalem.',
      fulfillmentAuthor: 'Apostle John (c. AD 95)',
      fulfillmentDate: 'c. AD 95',
      fulfillmentSetting: 'Exile on Patmos.',
      redemptiveBridge: 'From the piercing at Calvary to the universal revelation of the pierced King.',
    },
  },

  // Zechariah 12:10 -> Matthew 24:30
  'zec-12-10_Matthew 24:30': {
    id: 'zec-12-10_Matthew 24:30',
    anchorRef: 'Zechariah 12:10',
    targetRef: 'Matthew 24:30',
    who: 'Authorship & Context: Zechariah; Jesus in the Olivet Discourse (recorded by Matthew c. AD 60–68). Identified Characters: Jesus the Son of Man; the disciples; and all the tribes of the earth. Christological Subject & Referent: Jesus Christ coming in power and great glory. Redemptive Purpose: To prepare believers for the sudden, glorious appearing of the Son of Man.',
    what: 'Jesus\' citation of Zechariah 12:10 in the Olivet Discourse in Matthew 24:30: "And then shall appear the sign of the Son of man in heaven: and then shall all the tribes of the earth mourn, and they shall see the Son of man coming in the clouds of heaven with power and great glory."',
    when: 'Source: Post-Exilic Era (c. 520 BC). Target: Olivet Discourse (c. AD 30) on Mount of Olives.',
    how: 'Eschatological prophecy. Jesus applies Zechariah\'s phrase καὶ τότε κόψονται πᾶσαι αἱ φυλαὶ τῆς γῆς ("and then all the tribes of the earth shall mourn") to His glorious advent. The mourning is both the sorrow of unprepared sinners and the repentant mourning of those who recognize the One they rejected.',
    why: 'To warn humanity that judgment will be undeniable and universal.',
    ultimatePoint: 'The pierced Messiah will appear in glory on the clouds of heaven, causing all the tribes of the earth to mourn.',
    personalRelevance: 'Why you need to know this: The return of Jesus will not be a secret or ambiguous event; it will be cosmic and unmistakable. What it does for you: Keeps you alert, watchful, and steadfast in faith amidst end-time deception. Relationship with Jesus: Living in daily readiness to meet your King.',
    historicalContext: {
      sourceAuthor: 'Prophet Zechariah (c. 520 BC)',
      sourceDate: 'c. 520 BC',
      sourceSetting: 'Jerusalem restoration.',
      fulfillmentAuthor: 'Apostle Matthew (c. AD 60–68, recording Jesus c. AD 30)',
      fulfillmentDate: 'c. AD 30',
      fulfillmentSetting: 'Mount of Olives overlooking the Temple.',
      redemptiveBridge: 'The prophetic mourning of Zechariah leads directly to the cosmic climax of the Olivet Discourse.',
    },
  },
};
