/** Generated by scripts/exportBookJson.ts — do not edit by hand. */
export interface BookMeta {
  slug: string;
  name: string;
  chapters: number;
  verses: number;
}

export const BOOK_REGISTRY: BookMeta[] = [
  {
    "slug": "gen",
    "name": "Genesis",
    "chapters": 50,
    "verses": 1533
  },
  {
    "slug": "exo",
    "name": "Exodus",
    "chapters": 40,
    "verses": 1213
  },
  {
    "slug": "lev",
    "name": "Leviticus",
    "chapters": 27,
    "verses": 859
  },
  {
    "slug": "num",
    "name": "Numbers",
    "chapters": 36,
    "verses": 1288
  },
  {
    "slug": "deu",
    "name": "Deuteronomy",
    "chapters": 34,
    "verses": 959
  },
  {
    "slug": "jos",
    "name": "Joshua",
    "chapters": 24,
    "verses": 658
  },
  {
    "slug": "jdg",
    "name": "Judges",
    "chapters": 21,
    "verses": 618
  },
  {
    "slug": "rut",
    "name": "Ruth",
    "chapters": 4,
    "verses": 85
  },
  {
    "slug": "1sa",
    "name": "1 Samuel",
    "chapters": 31,
    "verses": 811
  },
  {
    "slug": "2sa",
    "name": "2 Samuel",
    "chapters": 24,
    "verses": 695
  },
  {
    "slug": "1ki",
    "name": "1 Kings",
    "chapters": 22,
    "verses": 817
  },
  {
    "slug": "2ki",
    "name": "2 Kings",
    "chapters": 25,
    "verses": 719
  },
  {
    "slug": "1ch",
    "name": "1 Chronicles",
    "chapters": 29,
    "verses": 942
  },
  {
    "slug": "2ch",
    "name": "2 Chronicles",
    "chapters": 36,
    "verses": 822
  },
  {
    "slug": "ezr",
    "name": "Ezra",
    "chapters": 10,
    "verses": 280
  },
  {
    "slug": "neh",
    "name": "Nehemiah",
    "chapters": 13,
    "verses": 406
  },
  {
    "slug": "est",
    "name": "Esther",
    "chapters": 10,
    "verses": 167
  },
  {
    "slug": "job",
    "name": "Job",
    "chapters": 42,
    "verses": 1070
  },
  {
    "slug": "psa",
    "name": "Psalms",
    "chapters": 150,
    "verses": 2461
  },
  {
    "slug": "pro",
    "name": "Proverbs",
    "chapters": 31,
    "verses": 915
  },
  {
    "slug": "ecc",
    "name": "Ecclesiastes",
    "chapters": 12,
    "verses": 222
  },
  {
    "slug": "sng",
    "name": "Song of Solomon",
    "chapters": 8,
    "verses": 117
  },
  {
    "slug": "isa",
    "name": "Isaiah",
    "chapters": 66,
    "verses": 1292
  },
  {
    "slug": "jer",
    "name": "Jeremiah",
    "chapters": 52,
    "verses": 1364
  },
  {
    "slug": "lam",
    "name": "Lamentations",
    "chapters": 5,
    "verses": 154
  },
  {
    "slug": "ezk",
    "name": "Ezekiel",
    "chapters": 48,
    "verses": 1273
  },
  {
    "slug": "dan",
    "name": "Daniel",
    "chapters": 12,
    "verses": 357
  },
  {
    "slug": "hos",
    "name": "Hosea",
    "chapters": 14,
    "verses": 197
  },
  {
    "slug": "jol",
    "name": "Joel",
    "chapters": 3,
    "verses": 73
  },
  {
    "slug": "amo",
    "name": "Amos",
    "chapters": 9,
    "verses": 146
  },
  {
    "slug": "oba",
    "name": "Obadiah",
    "chapters": 1,
    "verses": 21
  },
  {
    "slug": "jon",
    "name": "Jonah",
    "chapters": 4,
    "verses": 48
  },
  {
    "slug": "mic",
    "name": "Micah",
    "chapters": 7,
    "verses": 105
  },
  {
    "slug": "nam",
    "name": "Nahum",
    "chapters": 3,
    "verses": 47
  },
  {
    "slug": "hab",
    "name": "Habakkuk",
    "chapters": 3,
    "verses": 56
  },
  {
    "slug": "zep",
    "name": "Zephaniah",
    "chapters": 3,
    "verses": 53
  },
  {
    "slug": "hag",
    "name": "Haggai",
    "chapters": 2,
    "verses": 38
  },
  {
    "slug": "zec",
    "name": "Zechariah",
    "chapters": 14,
    "verses": 211
  },
  {
    "slug": "mal",
    "name": "Malachi",
    "chapters": 4,
    "verses": 55
  },
  {
    "slug": "mat",
    "name": "Matthew",
    "chapters": 28,
    "verses": 1071
  },
  {
    "slug": "mrk",
    "name": "Mark",
    "chapters": 16,
    "verses": 675
  },
  {
    "slug": "luk",
    "name": "Luke",
    "chapters": 24,
    "verses": 1151
  },
  {
    "slug": "joh",
    "name": "John",
    "chapters": 21,
    "verses": 879
  },
  {
    "slug": "act",
    "name": "Acts",
    "chapters": 28,
    "verses": 1007
  },
  {
    "slug": "rom",
    "name": "Romans",
    "chapters": 16,
    "verses": 433
  },
  {
    "slug": "1co",
    "name": "1 Corinthians",
    "chapters": 16,
    "verses": 437
  },
  {
    "slug": "2co",
    "name": "2 Corinthians",
    "chapters": 13,
    "verses": 257
  },
  {
    "slug": "gal",
    "name": "Galatians",
    "chapters": 6,
    "verses": 149
  },
  {
    "slug": "eph",
    "name": "Ephesians",
    "chapters": 6,
    "verses": 155
  },
  {
    "slug": "php",
    "name": "Philippians",
    "chapters": 4,
    "verses": 104
  },
  {
    "slug": "col",
    "name": "Colossians",
    "chapters": 4,
    "verses": 95
  },
  {
    "slug": "1th",
    "name": "1 Thessalonians",
    "chapters": 5,
    "verses": 89
  },
  {
    "slug": "2th",
    "name": "2 Thessalonians",
    "chapters": 3,
    "verses": 47
  },
  {
    "slug": "1ti",
    "name": "1 Timothy",
    "chapters": 6,
    "verses": 113
  },
  {
    "slug": "2ti",
    "name": "2 Timothy",
    "chapters": 4,
    "verses": 83
  },
  {
    "slug": "tit",
    "name": "Titus",
    "chapters": 3,
    "verses": 46
  },
  {
    "slug": "phm",
    "name": "Philemon",
    "chapters": 1,
    "verses": 25
  },
  {
    "slug": "heb",
    "name": "Hebrews",
    "chapters": 13,
    "verses": 303
  },
  {
    "slug": "jam",
    "name": "James",
    "chapters": 5,
    "verses": 108
  },
  {
    "slug": "1pe",
    "name": "1 Peter",
    "chapters": 5,
    "verses": 105
  },
  {
    "slug": "2pe",
    "name": "2 Peter",
    "chapters": 3,
    "verses": 61
  },
  {
    "slug": "1jn",
    "name": "1 John",
    "chapters": 5,
    "verses": 105
  },
  {
    "slug": "2jn",
    "name": "2 John",
    "chapters": 1,
    "verses": 13
  },
  {
    "slug": "3jn",
    "name": "3 John",
    "chapters": 1,
    "verses": 15
  },
  {
    "slug": "jud",
    "name": "Jude",
    "chapters": 1,
    "verses": 25
  },
  {
    "slug": "rev",
    "name": "Revelation",
    "chapters": 22,
    "verses": 404
  }
];

export const BOOK_BY_NAME: Record<string, BookMeta> = Object.fromEntries(
  BOOK_REGISTRY.map(b => [b.name, b])
);

